/* src: 2017-01-19 14:38:37 */
/* gen: 2017-01-19 17:43:32 */
(function(){function Lb(f,k,r,v){var p=!1,D=!1;f=nb({event_type:"getBlockNum",event:f},k,void 0);Mb(f,function(f,k){p=!0;if(D)return!1;r(f,k)});setTimeout(function(){D=!0;if(p)return!1;v()},250)}function Ta(f,k,r,v,p){f={M:v||!1,v:p||!1,src:f,ca:k,da:r};f[Nb]=Ia();return f}function nb(f,k,r){var v=k.ca,p=k.da,D=k.src;f.type="event";f.rnd=Ia();f.prefix=sa[0];f.broadcast=r||!1;k.M&&(f["for"]=k.M);k=!1;r=null;if(!~Ob.indexOf("iphone"))try{r="*"==v?!0:D.location.protocol+"//"+D.location.hostname==v}catch(C){}if(null===
r||r)D.postMessage(p+"|"+JSON.stringify(f),v),k=f.rnd;return k}function Pb(f,k){var r;k=k||{};r=r||function(f){return f};C(O,function(v){if(~O[v].o.indexOf(f)||~O[v].o.indexOf("*")){var p=r(S(k),M(O[v].K[f],{}));!1!==p&&nb({event_type:f,event:p},O[v].ea)}})}function Qb(f,k,r){var v=Ta(f.source,f.origin,M(k.prefix,r),M(k.rnd),M(k["for"]));v.v&&U(za[v.v])?za[v.v]&&(za[v.v](k.event,v),za[v.v]=null):C(Aa,function(f){if(Aa[f]&&~Aa[f].o.indexOf(k.event_type)&&0===Aa[f].ha(k.event,v))return!1})}function Mb(f,
k){za[f]=k}function Rb(){}function Ia(){var f;f=99*Math.random();if(U(void 0)){var k;k=Math.pow(10,void 0);f=Math.round(f*k)/k}else f=Math.round(f);return(new Date).getTime()%1E7*100+f}function U(f){return"undefined"!=typeof f}function M(f,k){k=U(k)?k:!1;return U(f)?f:k}function Sb(f,k){C(k,function(r){f[r]=k[r]})}function C(f,k){for(var r in f)if(f.hasOwnProperty(r)&&"length"!==r&&!1===k.call(f[r],r,f[r]))break}function Ua(f){for(var k={},r=[],v=f.length,p=0,D=0;D<v;D++){var C=f[D];1!==k[C]&&(k[C]=
1,r[p++]=C)}return r}function S(f,k){if(null==f||"object"!==typeof f)return f;if(void 0==k)k=[];else{var r,v=k.length;for(r=0;r<v;r++)if(f===k[r])return f}k.push(f);if("function"==typeof f.clone)return f.clone(!0);if("[object Array]"==Object.prototype.toString.call(f)){v=f.slice();for(r=v.length;r--;)v[r]=S(v[r],k);return v}if(f instanceof Date)return new Date(f.getTime());if(f instanceof RegExp)return new RegExp(f);if(f.nodeType&&"function"==typeof f.cloneNode)return f.cloneNode(!0);r=Object.getPrototypeOf?
Object.getPrototypeOf(f):f.__proto__;r||(r=f.constructor.prototype);var v=Va(r),p;for(p in f)v[p]=S(f[p],k);return v}function Wa(f,k){function r(){z({"div[id^=adriver_banner_]":"adriver","div[id^=AdFox_banner_]":"adfox","iframe[id^=AdFox_plug_]":"adfox","ins.adsbygoogle[data-ad-client^=ca-pub-3104790387792468]":"npm","ins[id^=aswift_]>ins[id^=aswift_]>iframe":"adsense","div[id^=div-gpt]>div[id^=google_ads_iframe_]>iframe[id^=google_ads_iframe_]":"dfp","div[id^=eplAdDivBanner]>iframe[id^=ifr]":"e-planning"},
function(a,b){var c=t.querySelectorAll(a);c.length&&z(c,function(a){if(1==c[a].getAttribute("data-___lx_atf"))return!0;if(ha()>Ba(c[a]).top){var d=ob(c[a]);ia(c[a]);d&&100<d.height&&(Xa(c[a],"data-___lx_atf",1),v(c[a],{sid:pb,type:b,h:d.height,w:d.width}))}else return!1})})}function v(a,b){b=b||{};setTimeout(function(a,b){return function(){T(P+"luxupcdna.com/npm_mobile_atf_problems/?rt="+Z()+"&loc="+encodeURIComponent(t.location.href)+xc(b),function(){})}}(a,b),0)}function p(a,b){var c=!1;if(!a||
!~b.indexOf("js/adsbygoogle.js"))return c;var e=ob(a),d=ob(a.parentNode),w=320;e&&e.width&&320>e.width?w=300:d&&d.width&&320>d.width&&(w=300);e='style="display:inline-block;width:'+w+'px;height:100px;"';d=/style="display: *?inline-block; *?width: *?\d+?px; *?height: *?\d+?px;"/m;/data-ad-format="(\w|,)+?"/m.test(b)&&(c=b.replace('style="display:block"',""),c=c.replace('style="display:inline-block;"',e),c=c.replace(/data-ad-format="(\w|,)+?"/mg,""));!(new RegExp('style="display:inline-block;width:'+
w+'px;height:100px;"',"m")).test(b)&&d.test(b)&&(c=b.replace(d,e));c&&(e=/data-alternate-ad-url="(.+?)"/mg,d=e.exec(c),null!=d&&(c=c.replace(e,'data-alternate-ad-url="$1'+(~d[1].indexOf("?")?"&":"?")+"w="+w+'&h=100&js_resize=1"')));return c}function D(a){for(var b=a.c.I.length,c=la(a.ai_min_space),e=la(a.ai_1_space),d=null,w=null,n=!1,g=b?Tb(a.c.I[b-1].a):0;!n;){d=a.c.m.shift();if(!d)break;w=Tb(d);(n=(b?g+c:e)<w)&&a.c.F&&a.c.F.length&&z(a.c.F,function(a,b){z(b.Ja,function(a,c){var d=Ba(c).top,e=d+
u(c.offsetHeight);if(d>w&&d-b.oa<w||e<w&&e+b.oa>w||d==w||e==w)return n=!1});if(!n)return!1})}return n?d:null}function C(a,b,c){c=c||!1;if(!(a.c.H&&!b||a.c.I.length>=a.ai_max_count)&&(a.c.H=!0,null==a.c.m&&(a.c.m=t.querySelectorAll(a.location),a.c.m&&a.c.m.length&&(a.c.m=Array.prototype.slice.call(a.c.m,0)),a.P&&z(a.c.m,function(b,c){ha()>Ba(c).top&&a.c.m.splice(b,1)})),a.c.m.length)){if(l(a.ai_border_check)&&null==a.c.F){a.c.F=[];b=a.ai_border_check;b=b.split(",");var e=la(a.ai_min_space);z(b,function(b,
c){var d=e;~c.indexOf(":")&&(c=c.split(":"),d=la(c[1]),c=c[0]);var n=t.querySelectorAll(c);n&&n.length&&a.c.F.push({Ya:c,oa:d,Ja:n})})}var d=D(a);b=null;if(d){b={};var w=c?c:1+a.c.I.length,n=a.c.id+"."+w;b.a=H("div");b.a.id=a.id;b.a.setAttribute("data-cnt",w);b.a.className="__lxG__multi __lxG__multi_"+a.id;a.c.ma?a.c.ma(d,b.a,{}):d.parentNode.insertBefore(b.a,d.nextSibling);d={};a.c.source?("iframe"==a.c.Oa?(a.c.qa&&Q(b.a,a.c.qa),aa(b.a,a.c.source,a.c.width,a.c.height,t,!1,l(a.c.Pa,!0))):Q(b.a,a.c.source),
K(a.c)):(d=function(a,b,c){return function(){c.Za=null;T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(a){return function(){a.c.H=!1;a.c.m.length&&Ha(a)&&C(a,!0)}}(b))}}(n,a,d),c?d():yc("getBlockNum",{ids:[n]},Ja,function(a,b,c){return function(d){d=d.ids;d.length&&(a=d[0]["new"],b.a.setAttribute("data-cnt",d[0].cnt));T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(a){return function(){a.c.H=!1;a.c.m.length&&Ha(a)&&C(a,!0)}}(c));return-1}}(n,b,a),d));a.c.I.push(b);l(a.refresh)&&(a.l=
setTimeout(zc(a,w),1E3*a.refresh))}l(a.ai_clone_source)&&b&&a.c.m.length&&Ha(a)&&C(a,!0);a.c.H=!1}}function Ha(a){var b=a.c.I;if(!b||!b.length||b.length>=a.ai_max_count)return!1;var b=Tb(b[b.length-1].a),c=la(a.ai_min_space),e=u(!Ka||h.opera||Ya||"unknown"!=ma()?L.scrollTop:ba.scrollTop);return b+c<e+ha()*(a.ai_preload+1)}function la(a){a=l(a,!1);if(!1!==a){var b=/((\d|\.|,)+?)s/im.exec(a);null!=b?a=Math.round(parseFloat(b[1])*ha()):a=u(a)}return a}function O(a,b,c){.1<(b-a.a.volume)*c?(a.a.volume=
V(a.a.volume+.1*c,2),na[a.g]=setTimeout(function(){O(a,b,c)},25)):a.a.volume=b}function td(a){na[a.g]&&clearTimeout(na[a.g]);na[a.g]=setTimeout(function(){0<a.a.volume&&O(a,0,-1)},100)}function N(a){na[a.g]&&clearTimeout(na[a.g]);na[a.g]=setTimeout(function(){1>a.a.volume&&O(a,.6,1)},100)}function Ac(a){U(a,-1,function(){return function(){Za(h,"focus scroll",a.va);delete na[a.g];delete La[a.g];delete $a[a.g];a.j.ka?a.A.parentNode.removeChild(a.A):(a.href.parentNode.removeChild(a.href),a.Z.parentNode.removeChild(a.Z),
a.W.parentNode.removeChild(a.W),a.U.parentNode.removeChild(a.U),a.T.parentNode.removeChild(a.T))}}())}function Ma(a,b){var c=b.type;if("pause"!=c||a.a.duration!=a.a.currentTime){"play"==c&&0==a.a.currentTime&&(c="started");if("timeupdate"==c){if(a.j.J)for(var e in a.j.J)if(a.j.J.hasOwnProperty(e)){var d=u(e.replace("_",""));if(a.a.duration*d/100<=a.a.currentTime){for(d=a.j.J[e].length;d--;)H("img").src=a.j.J[e][d];delete a.j.J[e]}}100!=a.j.ja&&!a.Y&&a.a.duration*a.j.ja/100<=a.a.currentTime&&(a.Y=
!0,setTimeout(function(){T(a.j.ua,function(){})},0))}"started"==c&&setTimeout(function(){T(a.j.Ra,function(){})},0);"ended"==c&&(a.Y||setTimeout(function(){T(a.j.ua,function(){})},0),Ac(a))}}function S(a){if(!a.B){for(var b=!1,c=ha(),e=a.a.getClientRects(),d=0,w=e.length;d<w;d++){var n=e[d];if(0<=n.top&&n.top<c){b=!0;break}}b&&U(a,1,function(){return function(){M(a)}}())}a.B&&a.a.duration!=a.a.currentTime&&((b=Bc(a.a))&&a.a.paused?a.a.play():b||a.a.pause())}function M(a){La[a.g]&&clearTimeout(La[a.g]);
La[a.g]=setTimeout(function(){S(a)},50)}function U(a,b,c){$a[a.g]&&clearTimeout($a[a.g]);var e=ia(a.A),d=u(e.height),w=a.j.ka?0:120;1==b&&d<a.a.height||-1==b&&d>w?(a.A.style.height=d+5*b+A,1==b?a.A.style.opacity=parseFloat(e.opacity)+V(1/(a.a.height/5),3)*b:(e=ia(a.href),a.href.style.opacity=parseFloat(e.opacity)+V(1/((a.a.height-w)/5),3)*b,a.Z.style.opacity=a.href.style.opacity,a.W.style.opacity=a.href.style.opacity,a.U.style.opacity=a.href.style.opacity,a.T.style.opacity=a.href.style.opacity),$a[a.g]=
setTimeout(function(){U(a,b,c)},10)):(1==b?(a.B=1==b,a.A.style.opacity=u(a.B)):-1==b&&0==w&&(a.A.style.display="none"),c())}function sa(a,b){if(!Cc){Cc=!0;var c=H("link");c.setAttribute("rel","stylesheet");c.setAttribute(Ub,"text/css");c.href=P+"s.luxupcdna.com/images/i/video26/videostyle.css";ab.appendChild(c)}var e={g:Z(),B:!1};na[e.g]=La[e.g]=$a[e.g]=!1;e.j=b;e.Y=!1;c=H("div");c.style.cssText=b.ya;c.style.width=b.V+A;c.style.height=0+A;c.style.margin="0 auto";c.style.textAlign="center";c.style.display=
"block";c.style.overflow="hidden";c.style.opacity=0;c.style.position="relative";J(c,"lx_amn_inlvid");var d=H("a");d.href="javascript:void(0);";J(d,"ico");d.appendChild(H("span"));var w=H("a");w.href=b.ia;w.target="_blank";J(w,"vid");var n=H("video");n.width=b.V;n.height=Dc(b.V/(b.Ta/b.Qa));n.controls=!1;n.autoplay=!1;n.volume=0;var g=H("source");g.src=b.Sa;n.appendChild(g);e.a=n;e.A=c;e.href=w;e.Z=d;e.nextSibling=a.nextSibling;e.previousSibling=a;g=H("a");g.href="javascript:void(0);";g.innerHTML=
"\u0417\u0430\u043a\u0440\u044b\u0442\u044c";E(g,"click",function(){return function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;Ac(e);return!1}}());J(g,"cls");e.W=g;b.Ba&&(g.style.display="none");var f=H("a");f.href="javascript:void(0);";f.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">\u0420\u0435\u043a\u043b\u0430\u043c\u0430</span>';J(f,"adv");e.U=f;b.Ca&&(f.style.display="none");var m=H("a");m.href="javascript:void(0);";m.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">'+
e.j.pa+"</span>";J(m,"adv_txt");e.T=m;e.j.pa||(m.style.display="none");var l=H("div");J(l,"dsc");l.innerHTML='<span><a href="http://video.adlabsnetworks.com/?utm_source=partners&utm_medium=logo" target="_blank">Powered by</a></span>';var k=H("a");k.href=b.ia;k.target="_blank";l.appendChild(k);k.innerHTML="\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0440\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f";E(n,"play pause ended timeupdate",
function(){return function(a){Ma(e,a)}}());E(n,"mouseover",function(){return function(){N(e)}}());E(n,"mouseout",function(){return function(){td(e)}}());E(w,"click",function(){return function(){e.a.pause();return!0}}());e.va=function(){return function(){M(e)}}();E(h,"focus scroll",e.va);w.appendChild(n);c.appendChild(g);c.appendChild(f);c.appendChild(m);c.appendChild(d);c.appendChild(w);c.appendChild(l);a.parentNode.insertBefore(c,a.nextSibling);La[e.g]=setTimeout(function(){M(e)},50)}function da(a){var b=
new Date,c=b.getTime();b.setTime(c+2592E6);ca.set(Vb,a,b,"/");ca.set(Ec,ca.get(Fc,0),b,"/");ca.set(Fc,c,b,"/")}function zc(a,b){return function(){if(a.u)return!1;a.l&&clearTimeout(a.l);a.u=!0;var c=null;z(F,function(b){if(F[b]===a)return c=b.replace("_",""),!1});!1!==l(a.refresh_limit)&&a.refresh_limit--;T(P+"luxupcdna.com/multishows/"+c+(b?"."+b:"")+"/"+ta(),function(){a.u=!1})}}function oa(a,b){q(h.__lxG__.multishows_params)&&l(h.__lxG__.multishows_params.preventautorefresh)||!l(a.refresh)||
!l(a.refresh_limit,!0)||(a.l=setTimeout(zc(a,b||null),1E3*a.refresh))}function za(a,b,c){b.buffer={x:[],y:[]};b.buffer.Aa=function(a,b,c){return function(a){if(a||h.event)a=a||h.event,a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;c.style.display="none";return b.G=!0}}(a,b,c);E(c.querySelectorAll(".lx_close"),"click",b.buffer.Aa);b.buffer.show=function(a,b,c){return function(n){var g=n.pageY;b.buffer.x.push(n.pageX);b.buffer.y.push(g);b.buffer.x=b.buffer.x.slice(-5);b.buffer.y=b.buffer.y.slice(-5);
var h=!1;z(b.buffer.y,function(a,c){if(u(a))if(c<=b.buffer.y[a-1])h=!0;else return h=!1});h&&30>g&&(Za(t,"mousemove",b.buffer.show),c.style.display="block",K(a))}}(a,b,c);E(t,"mousemove",b.buffer.show)}function Gc(a){for(var b=!1,c=bb("meta",!0),e=c.length;e--;)if(q(c[e].name)&&"viewport"==c[e].name){var d=c[e].content;if(~d.indexOf(a)&&(d=(new RegExp(a+" *?= *?(.+?)(?:[, ]|$)","m")).exec(d),null!=d)){b=d[1];break}}return b}function pa(){if(-1===qb){qb=!1;for(var a=bb("meta",!0),b=a.length;b--;)if(q(a[b].content)){var c=
a[b].content;if(~c.indexOf("width=device-width")||~c.indexOf("initial-scale=1")||~c.indexOf("user-scalable=no")){qb=!0;break}}}return qb}function Aa(a){var b=ga();b&&(Wb=b.getAttribute("content"));a=a||"width=device-width";b?Xa(b,"content",a):(t.getElementsByTagName("head").length||t.insertBefore(H("head"),t.getElementsByTagName("body")[0]),b=H("meta"),b.name="viewport",b.content=a,bb("head").appendChild(b))}function ga(){for(var a=!1,b=bb("meta",!0),c=b.length;c--;)if(q(b[c].name)&&"viewport"==b[c].name){a=
b[c];break}return a}function Ta(a){return function(){if(a.u)return!1;a.l&&clearTimeout(a.l);a.u=!0;Hc(a.N)}}function Ia(a,b){setTimeout(function(){var c=parseInt(a.style.right);0<b&&0==c||0>b&&c==Xb(a)||(c+=6*b,0<c&&(c=0),c<Xb(a)&&(c=Xb(a)),a.style.right=c+"px",Ia(a,b))},10)}function Va(a){return function(){ua()?J(a.a,"lxm_landscape"):cb(a.a,"lxm_landscape");t.getElementById("lx_dbg_fullscreen")&&(t.getElementById("lx_dbg_fullscreen").innerHTML=a.a.className);return!1}}function Wa(a){return function(b){b.stopPropagation();
var c=B("lx_links_position",a.a)[0];Yb(c,"anishow")?(J(c,"anihide"),cb(c,"anishow")):(J(c,"anishow"),cb(c,"anihide"));b.preventDefault();return!1}}function jb(){return function(a){a.stopPropagation();var b=q(this.style)?u(l(this.style.right,0)):0;return u(a.pageX)-u(this.offsetLeft)<this.getAttribute("triggerWidth")?(b!=this.getAttribute("baseStyleRight")&&0!=b||Ia(this,0==b?-1:1),a.preventDefault(),!1):!0}}function lb(a,b){return function(c){if(c||h.event)c=c||h.event,c.stopPropagation?c.stopPropagation():
c.cancelBubble=!0,c.preventDefault&&c.preventDefault();c=B("lxm_sl",a.a)[0];c.style.display="";c=B("lxm_button",c)[0];c.href=b.href;c.title=b.title;return!1}}function mb(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;B("lxm_sl",a.a)[0].style.display="";return!1}}function nb(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.a.style.display="none";a.G=!0;a.$&&(b=ga(),Wb?Xa(b,"content",
Wb):b.parentNode.removeChild(b));if(db(a.closeTimeout)&&(b=db(a.closeTimeout))){var c=new Date;c.setTime(c.getTime()+6E4*b);ca.set("_lxblockignore_"+a.N,1,c,"/")}return!0}}function Ua(a,b,c){!1!==c&&J(a,"lxm_"+b+"_"+(.5*Math.ceil(parseFloat(c)/.5)).toString().replace(".","_"))}function Kb(){var a=ma(),b=kb(),c=1,c=pa()?1/b:(1.144>b?1:2.75<b?1.26:4.431914*Math.pow(b,8)-65.6671503*Math.pow(b,7)+417.3583138*Math.pow(b,6)-1484.928018*Math.pow(b,5)+3233.105604*Math.pow(b,4)-4410.2163548*Math.pow(b,3)+
3680.9724495*Math.pow(b,2)-1719.2504263*b+345.6426082)/b;a==R&&3>Ca&&!ua()?c=1.3*b:ua()&&(c*=1.15);return c=V(100*c)}function kb(){if(Ic!=Zb){var a=ma(),b=1,c=pa()?1:window.devicePixelRatio;a==eb&&~ja.indexOf("iphone")&&!pa()&&(c=2);b=ba.clientWidth/h.innerWidth/c;if(~ja.indexOf("ipad")||a==R&&Da&&1<c)b*=c;ua()&&a==R&&!pa()?b*=2:ua()&&a==R&&pa()&&(b*=.85);!ua()&&Da&&a==R?b/=(Ca(),1.5):ua()&&Da&&a==R&&!pa()&&(b/=4<=Ca()?1.75:1.5);Jc=V(100*b)/100;Ic=Zb}return Jc}function ua(){var a=ma(),b=0===window.orientation||
180===window.orientation;return Da&&a==R&&4<=Ca()?!b:Da&&a==R?b:!b}function ma(){if(!rb){rb="unknown";for(var a=[[R,R],["ipad",eb],["iphone",eb],["ipod",eb]],b=0;b<a.length;b++)if(~ja.indexOf(a[b][0])){rb=a[b][1];break}}return rb}function Ca(){if(!1===sb){var a=ma();sb=0;a==R&&(sb=parseFloat(ja.slice(ja.indexOf(R)+8)))}return sb}function Kc(a){if(!$b){var b=0;$b=!0;Zb++;for(var c in W)if(W.hasOwnProperty(c)){var e=W[c];if(!e.na&&!e.$&&!e.G){var d=e.a,w=kb(),n=Kb(),g=[h.pageXOffset,h.pageYOffset],
f=[h.pageXOffset,h.pageYOffset+h.innerHeight];d.style.width=g[0]+h.innerWidth-g[0]+A;ma()==R&&4<=Ca()||(d.style.left=g[0]+A,d.style.top=e.Ea?f[1]-d.offsetHeight+A:g[1]+A);ua()?J(d,"lxm_landscape"):cb(d,"lxm_landscape");w=Math.ceil(e.Da/w);d.style.height=w+A;tb(e.Ga,"height",w+A);tb(e.Ia,"lineHeight",w+A);e.fa&&(d=Dc(w*(pa()?.8:.95))+A,e.fa.style.height=d,e.fa.style.width=d);d=pa()?100:50>n?80:100;tb(e.Fa,"fontSize",n+"%");tb(e.Ha,"lineHeight",d+"%");b++}}b&&a&&(ac&&clearTimeout(ac),ac=setTimeout(function(){Kc(!1)},
250));$b=!1}}function Lc(){bc&&clearTimeout(bc);bc=setTimeout(function(){Kc(!0)},250)}function Lb(a,b){var c=cc(a.a);if(b){for(var e in c)c.hasOwnProperty(e)&&u(c[e])&&"lxm_"==e.substring(0,4)&&J(a.a,e);J(a.a,"lxm_os_"+ma());pa()&&J(a.a,"lxm_meta_set");q(h.devicePixelRatio)&&J(a.a,"lxm_pixel_ratio_"+Math.ceil(h.devicePixelRatio))}for(var d=B("lxm_js_block_close",a.a),w=d.length;w--;)E(d[w],ea,nb(a));a.na=!1;a.$=!1;if(db(c.lxm_fullscreen)){a.$=!0;Aa();d=B("lxm_sl_trigger",a.a);for(w=d.length;w--;)E(d[w],
ea,lb(a,d[w]));var n=B("lxm_sl",a.a)[0],c=B("lxm_button_close",n)[0];E(c,ea,function(){return function(){n.style.display="none"}}());q(screen.width)&&J(a.a,"lxm_scr_"+250*Math.ceil(Math.max(screen.width,screen.height)/250));c=h.innerHeight||0;J(a.a,"lxm_scr_width_"+100*Math.ceil((h.innerWidth||0)/100));J(a.a,"lxm_scr_height_"+100*Math.ceil(c/100));Ua(a.a,"minscale",Gc("minimum-scale"));Ua(a.a,"initscale",Gc("initial-scale"));c="lxm_zoom_"+(.25*Math.ceil(ba.clientWidth/h.innerWidth/.25)).toString().replace(".",
"_");J(a.a,c);c=B("lx_hide_logo",a.a);for(d=c.length;d--;)E(c[d],ea,Wa(a));c=Va(a);d=["orientationchange","touchmove","touchend",Na,"resize"];for(e in d)d.hasOwnProperty(e)&&E(h,d[e],c);c()}else{d=B("lxm_sl_trigger",a.a);for(w=d.length;w--;)E(d[w],ea,mb(a));if(db(c.lxm_static))for(a.na=!0,c=B("lxm_banner_sc",a.a),d=c.length;d--;)E(c[d],ea,jb());else{b&&(ma()==R&&4<=Ca()||(a.a.style.position=ub,a.a.style[Mc]="auto"),a.Da=db(c.initheight),a.Ea=Yb(a.a,"lxm_bottom"),a.fa=Yb(a.a,"lxm_tizer")?B("lxm_tizer_img",
a.a)[0]:!1,a.Fa=B("lxm_js_fontsize",a.a),a.Ha=B("lxm_js_lineheight",a.a),a.Ia=B("lxm_js_lineheightpx",a.a),a.Ga=B("lxm_js_height",a.a));if(!Nc){if(ma()==R&&3>Ca())e=H("meta"),e.name="viewport",e.content="width=device-width",t.head.appendChild(e);else for(e in d=["orientationchange","touchmove","touchend",Na,"resize"],d)d.hasOwnProperty(e)&&E(h,d[e],Lc);Nc=!0}q(a.refresh)&&a.refresh&&(a.l&&clearTimeout(a.l),a.l=setTimeout(Ta(a),1E3*a.refresh));Lc()}}}function dc(a,b){a.B=!1;q(a.D)&&clearInterval(a.D);
clearTimeout(a.l);a.L&&clearTimeout(a.L);a.D=setInterval(function(){var c=Oc(a),e=c-22;c>=-a.width&&e>-a.width?(a.O=!0,a.a.style[a.side]=e+A):(clearInterval(a.D),a.O=!1,a.a.style[a.side]=-a.width+A,a.a.style.display="none",q(b)&&b());vb&&wb(a)()},15)}function Mb(a){return function(){a.L&&clearTimeout(a.L);a.aa=!1;a.ba&&T(ec+encodeURIComponent(a.ba),function(){})}}function Nb(a){a.B=!0;q(a.D)&&clearInterval(a.D);clearTimeout(a.l);a.l=setTimeout(Pc(a),1E3*a.refresh);a.a.style.display="block";a.D=setInterval(function(){var b=
Oc(a),c=b+22;0>b&&0>c?(a.O=!0,a.a.style[a.side]=c+A):(clearInterval(a.D),a.O=!1,a.a.style[a.side]=0+A,a.aa&&(a.L=setTimeout(Mb(a),1E3)));vb&&wb(a)()},15)}function Oc(a){var b=0;return b=vb?a.a[a.side+"Offset"]:u(a.a.style[a.side])}function Qc(a){return function(){q(a.la)&&clearTimeout(a.la);a.la=setTimeout(wb(a),100)}}function wb(a){return function(){a.a[a.side+"Offset"]=u(a.a.style[a.side]);var b={bottom:!0};"left"==a.side&&(b.left=!0);"right"==a.side&&(b.right=!0);pinBlock(a.a,b)}}function Rc(a){return function(){if(!a.G&&
!a.u){var b=u(ba.scrollTop?ba.scrollTop:L.scrollTop);!a.B&&b>=a.limit?Nb(a):a.B&&b<a.limit&&dc(a)}}}function Pc(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;clearTimeout(a.l);a.u=!0;dc(a,function(){T(P+"luxupcdna.com/multishows/"+a.N+"/"+ta(),function(){})})}}function Ob(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.G=!0;dc(a);b=new Date;b.setTime(b.getTime()+5925924E4);ca.set(fc(),
1,b,"/")}}function Pb(a,b){b&&(E(t,Na,Rc(a)),vb&&(wb(a)(),E(h,"resize",Qc(a)),E(h,Na,Qc(a))));for(var c=B("close",a.a),e=c.length,d=0;d<e;d++)E(c[d],ea,Ob(a));c=B("ref",a.a);e=c.length;for(d=0;d<e;d++)E(c[d],ea,Pc(a))}function K(a,b){q(a.counters)&&(b=b||t,z(a.counters,function(a,e){H("img",b).src=e+"&_lxrnd_="+Z()}));3>=V(100*Math.random())&&Sc("https://pixel.adsafeprotected.com/jload?anId=924203&campId="+pb+"&placementId="+l(a.id,0)+"")}function Qb(a){z(a,function(a,c){if(l(c.id)){var e=c.id+(l(c.sub_id)?
"."+c.sub_id:"");null===Ea&&(Ea={});Ea[e]=c}else~ud.indexOf(l(c.type))?gc.push(c):~vd.indexOf(l(c.type))&&gc.push(c)})}function Rb(a,b,c){a=Oa("getBlockNum",a,b);Tc(a,function(a,b){c(a,b)})}function yc(a,b,c,e,d){var h=!1,n=!1;a=Oa(a,b,c);Tc(a,function(a,b){h=!0;if(n)return!1;e(a,b)});setTimeout(function(){n=!0;if(h)return!1;d()},250)}function xb(a,b,c,e,d){a={M:e||!1,v:d||!1,src:a,ca:b,da:c};a[wd]=Z();return a}function Oa(a,b,c){return yb("event",{event_type:a,event:b},c,void 0)}function yb(a,b,
c,e){var d=c.ca,h=c.da,n=c.src;b.type=a;b.rnd=Z();b.prefix=zb[0];b.broadcast=e||!1;c.M&&(b["for"]=c.M);a=!1;c=null;if(!~ja.indexOf("iphone"))try{c="*"==d?!0:n.location.protocol+"//"+n.location.hostname==d}catch(g){}if(null===c||c)n.postMessage(h+"|"+JSON.stringify(b),d),a=b.rnd;return a}function Sb(a,b){var c;b=b||{};c=c||function(a){return a};z(fa,function(e){if(~fa[e].o.indexOf(a)||~fa[e].o.indexOf("*")){var d=c(hc(b),l(fa[e].K[a],{}));!1!==d&&yb("event",{event_type:a,event:d},fa[e].ea)}})}function xd(a,
b,c){var e=xb(a.source,a.origin,l(b.prefix,c),l(b.rnd),l(b["for"]));e.v&&q(fb[e.v])?fb[e.v]&&(fb[e.v](b.event,e),fb[e.v]=null):z(gb,function(a){if(gb[a]&&~gb[a].o.indexOf(b.event_type)&&0===gb[a].ha(b.event,e))return!1})}function Tc(a,b){fb[a]=b}function va(a,b){a=Array.isArray(a)?a:[a];gb.push({o:a,ha:b})}function yd(a,b){b=b||h.event;var c=b.target,e=H("A");e.id="FakeLink";L.appendChild(e);var d=t.createEvent("MouseEvents");d.initMouseEvent("click",!!c,!0,h,1,!1,!1,!1,!1,!0,!1,!1,!1,!1,null);e.href=
a;e.target="_blank";e.dispatchEvent(d)}function zd(a){var b=h.open("about:blank",y+"popunder","toolbar=0,scrollbars=1,location=1,statusbar=1,menubar=0,resizable=1,top=0,left=0,width="+h.screen.availWidth+",height="+h.screen.availHeight+"");if(b){b.blur();try{b.opener.focus()}catch(c){}b.location=a}}function Uc(a){var b=h.open("about:blank",y+"popunder","resizable=1,toolbar=0,location=1,menubar=1,directories=0,width="+h.screen.availWidth+",height="+h.screen.availHeight+",scrollbars=1");b&&(b.blur(),
b.xa=function(c){with(c)Params=c.Va,Main=function(){q(window.mozPaintCount)&&window.open("about:blank").close();try{opener.window.focus()}catch(c){}b.location=a},Main()},b.xa(b),b.blur())}function Vc(){Pa&&clearTimeout(Pa);Pa=setTimeout(Ad,500)}function Ad(){Pa&&(clearTimeout(Pa),Pa=null);for(var a=Fa.length,b=0;b<a;b++)if(Fa[b]){var c=Fa[b][1];Bc(Fa[b][0])&&(delete Fa[b],T(ec+encodeURIComponent(c),function(){}))}}function Bc(a){if(0===a.offsetWidth||0===a.offsetHeight)return!1;for(var b=ha(),c=Ka&&
!h.opera?ba.clientWidth:L.clientWidth,e=a.getClientRects(),d=0,w=e.length;d<w;d++){var n=e[d],g=n.height?n.height:n.bottom-n.top,f=n.width?n.width:n.right-n.left,f=0<=n.left+.25*f&&n.left+.75*f<c;if(g=0<=n.top+.25*g&&n.top+.75*g<b&&f){n=t.elementFromPoint((n.left+n.right)/2,(n.top+n.bottom)/2);if(n===a)n=!0;else a:{if(n)for(n=n.parentNode;null!=n;){if(n==a){n=!0;break a}n=n.parentNode}n=!1}g=n}if(g)return!0}return!1}function ha(){return Ka&&!h.opera?ba.clientHeight:L.clientHeight}function Wc(a,b){function c(b){var c=
ia(a)["line-height"];"normal"==c?c=1.2*ic(ia(a)["font-size"]):/[a-z]+/im.test(c)?c=parseFloat(c):c=ic(ia(a)["font-size"])*parseFloat(c);return Math.ceil(c*b)}function e(b){var c=b.lastChild&&!b.lastChild.nodeValue&&b.lastChild.innerHTML?b.lastChild.innerHTML:b.lastChild.nodeValue;if(b.lastChild.children&&0<b.lastChild.children.length)return e(Array.prototype.slice.call(b.children).pop());if(b.lastChild&&c&&""!=c&&c!=n.S)return b.lastChild;b.lastChild.parentNode.removeChild(b.lastChild);return e(a)}
function d(b,c){if(c&&b){var g=!(b.nodeValue||!b.innerHTML),f=(g?b.innerHTML:b.nodeValue).replace(n.S,"");k||(0<m.length?l=m.shift():l="",k=f.split(l));1<k.length?(q=k.pop(),h(b,k.join(l),g)):k=null;if(k){if(a.clientHeight<=c)if(0<=m.length&&""!=l)h(b,k.join(l)+l+q,g),k=null;else return a.innerHTML}else""==l&&(h(b,"",g),b=e(a),m=n.ta.slice(0),l=m[0],q=k=null);return d(b,c)}}function h(a,b,c){c?a.innerHTML=b+n.S:a.nodeValue=b+n.S}b=b||{};var n={za:b.clamp||2,ga:"undefined"!=typeof b.ga?b.ga:!0,ta:[".",
"-","\u2013","\u2014"," "],S:"\u2026"},g=a.style,f=n.za,m=n.ta.slice(0),l=m[0],k,q;"undefined"!=typeof a.style.webkitLineClamp&&n.ga?(g.overflow="hidden",g.textOverflow="ellipsis",g.webkitBoxOrient="vertical",g.display="-webkit-box",g.webkitLineClamp=f):(g=c(f),g<=a.clientHeight&&d(e(a),g))}function Xc(a,b,c){var e=b||1;if(Qa.length){for(var d in Qa.Ma)Qa.Ma.hasOwnProperty(d)&&Za(h,"resize orientationchange",Qa[d]);Qa=[]}c.min=c.min||Number.NEGATIVE_INFINITY;c.max=c.max||Number.POSITIVE_INFINITY;
z(a,function(){function a(){var d=Math.round(Math.max(Math.min(ic(ia(b).width)/(10*e),parseFloat(c.max)),parseFloat(c.min)));b.style.fontSize=d+A}var b=this;a();Qa.push(a);E(h,"resize orientationchange",a)})}function Tb(a){return Ba(a).top+u(a.offsetHeight)}function Ba(a){a.getBoundingClientRect?(a=a.getBoundingClientRect(),a={top:Math.round(a.top+(h.pageYOffset||t.scrollTop||L.scrollTop)-(t.clientTop||L.clientTop||0)),left:Math.round(a.left+(h.pageXOffset||t.scrollLeft||L.scrollLeft)-(t.clientLeft||
L.clientLeft||0))}):a=jc(a);return a}function Yc(){}function aa(a,b,c,e,d,f,n,g){g=g||h;d=d||t;a instanceof g.HTMLElement&&(f=l(f,!1),n=l(n,!0),d=H("iframe",d),d.id=a.id+"_frame",n&&(d.sandbox="allow-same-origin allow-scripts allow-popups allow-forms"),q(c)&&(d.style.width=c+A),q(e)&&(d.style.height=e+A),d.setAttribute("allowtransparency","true"),d.setAttribute("marginwidth","0"),d.setAttribute("marginheight","0"),d.setAttribute("hspace","0"),d.setAttribute("vspace","0"),d.setAttribute("frameborder",
"0"),d.setAttribute("scrolling","no"),a.appendChild(d),f?d.src=b:(a=d.contentDocument,a.open(),a.write(b),a.close()))}function Q(a,b,c){var e;e=e||h;c=c||t;if(a instanceof e.HTMLElement&&(a.innerHTML=b)&&(e=a.childNodes)&&e.length){b=[];for(var d=0;e[d];d++){var f=e[d];!f.nodeName||"script"!==f.nodeName.toLowerCase()||f.type&&"text/javascript"!==f.type.toLowerCase()||b.push(e[d])}for(var n in b){e=b[n].parentNode?b[n].parentNode.removeChild(b[n]):b[n];var d=(d=c)||t,f=a||ab,g=H("script",d);g.type=
"text/javascript";if(q(e.src)&&e.src)g.src=e.src,g.className=e.className;else{var l=e.text||e.textContent||e.innerHTML||"";g.className=e.className;g.appendChild(d.createTextNode(l))}f.appendChild(g)}}}function wa(a){var b;b=b||t;var c=H("style",b);c.setAttribute("rel","stylesheet");c.setAttribute(Ub,"text/css");ab.appendChild(c);xa?c.styleSheet.cssText=a:c.appendChild(b.createTextNode(a))}function B(){}function ic(a){return parseFloat(a)}function u(a){return parseInt(a,10)}function V(a,b){if(q(b)){var c;
c=Math.pow(10,b);return Math.round(a*c)/c}return Math.round(a)}function Dc(a){return Math.floor(a)}function Z(){return(new Date).getTime()%1E7*100+V(99*Math.random())}function q(a){return"undefined"!=typeof a}function l(a,b){b=q(b)?b:!1;return q(a)?a:b}function db(a){return q(a)?u(a):!1}function Bd(a,b){z(b,function(c){a[c]=b[c]})}function bb(a,b,c){c=c||t;return b?c.getElementsByTagName(a):c.getElementsByTagName(a)[0]}function Xb(a){return a.getAttribute("baseStyleRight")}function Xa(a,b,c){a.setAttribute(b,
c+"")}function z(a,b){for(var c in a)if(a.hasOwnProperty(c)&&"length"!==c&&!1===b.call(a[c],c,a[c]))break}function Cd(a){a=a.split("+").join(" ");for(var b={},c,e=/[?&]?([^=]+)=([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1])]=decodeURIComponent(c[2]);return b}function E(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var e=b.length,d;for(d=0;d<e;d++)z(a,function(){this.addEventListener?this.addEventListener(b[d],c,!1):this.attachEvent("on"+b[d],c)})}}
function Za(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var e=b.length,d;for(d=0;d<e;d++)z(a,function(){this.detachEvent?this.detachEvent("on"+b[d],c):(this.removeEventListener(b[d],c,!0),this.removeEventListener(b[d],c))})}}function cb(a,b){b=b.split(" ");for(var c=0;c<b.length;c++)a.className=a.className.replace(new RegExp("\\b"+b[c]+"\\b","g"),"").replace(/\s+/g," ").replace(/(^ | $)/g,"")}function J(a,b){cb(a,b);b=b.split(" ");for(var c=0;c<b.length;c++)a.className+=
" "+b[c];a.className=a.className.trim()}function Yb(a,b){return(new RegExp("\\b"+b+"\\b","im")).test(a.className)}function H(a,b){b=b||t;return b.createElement(a)}function tb(a,b,c){if(a.length)for(var e=a.length;e--;)a[e].style[b]=c}function cc(a){a=B("lx_block_params",a);var b=a.length,c=[];if(b)for(var e=0;e<b;e++)for(var d=a[e].attributes,f=d.length,h;f--;)h=d[f],0===h.name.indexOf("data-")&&(c[h.name.replace("data-","")]=h.value);return c}function Zc(a){for(var b={},c=[],e=a.length,d=0,h=0;h<
e;h++){var f=a[h];1!==b[f]&&(b[f]=1,c[d++]=f)}return c}function hc(a,b){if(null==a||"object"!==typeof a)return a;if(void 0==b)b=[];else{var c,e=b.length;for(c=0;c<e;c++)if(a===b[c])return a}b.push(a);if("function"==typeof a.clone)return a.clone(!0);if("[object Array]"==Object.prototype.toString.call(a)){e=a.slice();for(c=e.length;c--;)e[c]=hc(e[c],b);return e}if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return new RegExp(a);if(a.nodeType&&"function"==typeof a.cloneNode)return a.cloneNode(!0);
c=Object.getPrototypeOf?Object.getPrototypeOf(a):a.__proto__;c||(c=a.constructor.prototype);var e=kc(c),d;for(d in a)e[d]=hc(a[d],b);return e}function T(a,b){b||(b=function(){});if((Ab||$c()&&ad)&&!/\bclickio\w*?\b/im.test(a)){if(Ab){var c="";try{c=h.top.location.href}catch(e){c=h.location.href}a+="&furl="+encodeURIComponent(c)}Dd(a,b)}else Sc(a,b)}function Hc(a,b){var c;b=b||ta();T(P+"luxupcdna.com/multishows/"+a+"/"+b,c||function(){})}function Sc(a,b){b||(b=function(){});var c=H("script");c.setAttribute(Ub,
"text/javascript");c.setAttribute("src",a);c.setAttribute("async","async");q(c)&&(xa?c.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||setTimeout(b,0)}:c.onload=function(){setTimeout(b,0)},ab.appendChild(c))}function Dd(a,b){b||(b=function(){});var c="ws"+("https:"==h.top.location.protocol?"s":"");a=a.replace(P,c+"://");a=a.replace(/wss?:\/\/([a-zA-Z0-9-.]+)\//img,c+"://$1/ws/");var c=new Worker(URL.createObjectURL(new Blob(['var r=null,s=new WebSocket("'+a+'");s.onmessage=function(e){if(e.data){postMessage(e.data);r=e.data;s.close();}};onmessage=function(e){if(e.data=="!"){close();};if(e.data=="?"&&r){postMessage(r);}}'],
{type:"application/javascript"}))),e=setInterval(function(a){return function(){a.postMessage("?")}}(c),50);c.onmessage=function(a,b,c){return function(e){a.onmessage=function(){};clearInterval(c);a.postMessage("!");Ed(e);b()}}(c,b,e)}function Ed(a){a=a.data;var b=H("script");b.type="text/javascript";b.appendChild(t.createTextNode(a));ab.appendChild(b)}function bd(){var a=!1,b=navigator,c=null;if(q(b.plugins)&&"object"==typeof b.plugins["Shockwave Flash"])!(c=b.plugins["Shockwave Flash"].description)||
q(b.mimeTypes)&&b.mimeTypes["application/x-shockwave-flash"]&&!b.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(c=c.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),a=[0,0,0],a[0]=u(c.replace(/^(.*)\..*$/,"$1")),a[1]=u(c.replace(/^.*\.(.*)\s.*$/,"$1")),a[2]=/[a-zA-Z]/.test(c)?u(c.replace(/^.*[a-zA-Z]+(.*)$/,"$1")):0);else if(q(h.ActiveXObject))try{if(c=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))c=c.split(" ")[1].split(","),a=[u(c[0]),u(c[1]),u(c[2])]}catch(e){}return a=
!1!==a?a.join("."):a}function Fd(){var a=bd(),b=["10","0","42"];if(!1===a)return!1;a=a.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||0;b[2]=parseInt(b[2],10)||0;return a[0]>b[0]||a[0]==b[0]&&a[1]>b[1]||a[0]==b[0]&&a[1]==b[1]&&a[2]>=b[2]?a.join("."):!1}function $c(){if(null!==Ga)return Ga;var a="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links";q(h.__lxG__.adbc)&&(a+=" "+h.__lxG__.adbc);var b=H("div");b.setAttribute("style","width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -10000px !important; ");
b.setAttribute("class",a);q(h.__lxG__.adbi)&&(b.id=h.__lxG__.adbi);L.appendChild(b);var a=!0,c=!1;q(h.__lxG__.adbh)?(b.innerHTML=h.__lxG__.adbh,q(h.__lxG__.adbhs)&&(c=b,b=b.querySelector(h.__lxG__.adbhs))):q(h.__lxG__.adbs)&&(a=!1,b=t.querySelector(h.__lxG__.adbs));Ga=!1;if(null!==L.getAttribute("abp")||null===b.offsetParent||0==b.offsetHeight||0==b.offsetLeft||0==b.offsetTop||0==b.offsetWidth||0==b.clientHeight||0==b.clientWidth)Ga=!0;if(!Ga){var e=ia(b);if("none"==e.getPropertyValue("display")||
"hidden"==e.getPropertyValue("visibility"))Ga=!0}a&&L.removeChild(b);c&&L.removeChild(c);return Ga}function ta(a){a=a||!1;var b="",b="?rt="+Z();t.referrer&&(b+="&r="+encodeURIComponent(t.referrer));qa&&(b+="&recurring=1");cd&&(b+="&flash="+encodeURIComponent(cd));xa&&(b+="&isie=1");"https:"==h.location.protocol&&(b+="&https=1");Bb&&(b+="&md="+encodeURIComponent(Bb));b+="&f="+ka;q(screen.width)&&(b+="&scr="+encodeURIComponent(screen.width+"x"+screen.height));q(h.innerWidth)&&(b+="&wnd="+encodeURIComponent(h.innerWidth+
"x"+h.innerHeight));$c()&&(b+="&bl=1");dd&&(dd=!1,b+="&add=1");ca.X(fc())&&(b+="&ignorefloat=1");lc.length&&(b+="&ignore="+lc.join(";"));q(h.__lxG__.multishows_params)&&(b+=xc(h.__lxG__.multishows_params));X.start&&(b+="&pbjs=1");a&&(a=Gd(a))&&(b+="&bids="+encodeURIComponent(a));return b+=h[y].multishowsAdd?"&"+h[y].multishowsAdd:""}function xc(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b}function ob(a){return q(a.getClientRects)&&
(a=a.getClientRects())&&q(a[0])&&q(a[0].right)&&q(a[0].left)?(a=a[0],{width:V(a.right-a.left),height:V(a.bottom-a.top)}):!1}function Hd(a,b){return function(){if(b&&""!=b.innerHTML){var c=ob(b);c&&T(P+"luxupcdna.com/area_size/?data="+a+","+c.width+","+c.height,function(){})}}}function mc(a,b){var c=t.getElementById(a);if(b){var e=t.querySelectorAll("#"+a),d;for(d in e)if(e.hasOwnProperty(d)&&"length"!=d&&e[d].getAttribute("data-cnt")==b){c=e[d];break}}return c}function nc(a,b){b=b||!1;var c=!1,
e=!0,e=ed(l(a.check)),d=l(a.location),h=l(a.location_max);if(e&&d)for(h?h=u(h):h=1,e=null,1<h?e=t.querySelectorAll(d):e=[t.querySelector(d)],d=0;d<e.length&&!(d+1>h);d++){var f=e[d];if(f){var g=H("div");g.id=a.id;var k=1+d;g.setAttribute("data-cnt",k);g.className="__lxG__multi __lxG__multi_"+a.id;Rb({ids:[a.id+"."+k]},Ja,function(a){return function(b){b=b.ids;b.length&&a.setAttribute("data-cnt",b[0].cnt);return-1}}(g));b?(f.innerHTML="",f.appendChild(g)):f.parentNode.insertBefore(g,f.nextSibling)}c||
(c=g)}return c}function Cb(a){var b=a.which?a.which:a.button;a=(xa?a.srcElement:a.target).nodeName.toLowerCase();"a"!=a&&"img"!=a||2==b||3==b||(clearTimeout(oc),oc=setTimeout(function(){oc=null;Db()},500))}function fd(a){a=a||!1;var b=[],c=[];Eb&&z(F,function(a){a=a.substr(1);X.bidding&&(~X.bidding.indexOf(a)||!~(""+a).indexOf(".")&&~X.bidding.indexOf(u(a)))?c.push(encodeURIComponent(a)):b.push(encodeURIComponent(a))});return a?[b.join(";"),c.join(";")]:b.join(";")}function Gd(a){a=a||fd();if(X.bids){var b=
!1,c="";z(a.split(";"),function(a,d){~gd.indexOf(d)||(z(X.bids,function(a,e){if(e.id==d){if(e.bids.length){var g=[];z(e.bids,function(a,b){g.push(b.join("_"))});c+=g.join(",");b=!0}gd.push(d);return!1}}),c+="-")});if(b)return c=c.substring(0,c.length-1)}return""}function hd(a){id(a.target?a.target:a.srcElement)}function Id(a){var b=/\/(i)\/(a??)(\d+?)\//m,c=b.exec(a);null==c&&(b=/\/(ii)\/(a??)(\d+?)\//m,c=b.exec(a));var e=!1,d=!1;null!=c&&16!=c[3]&&(e=u(c[3]),e=(2*(10*e+40)-40)/10,16<=e&&(e=16),d=
10*e+40,e=a.replace(b,"/$1/$2"+e+"/"));return{url:e,size:d}}function jd(a){var b=u("CSS1Compat"!=t.compatMode||h.opera?L.scrollTop:ba.scrollTop),c=u(b+ha()),e=u("CSS1Compat"!=t.compatMode||h.opera?L.scrollLeft:ba.scrollLeft),d=u(e+(Ka&&!h.opera?ba.clientWidth:L.clientWidth)),f=a.getClientRects()[0],l=V(f.top)+b,g=V(f.bottom)+b,k=V(f.left)+e,f=V(f.right)+e;l<b&&(a.style.top=u(a.style.top)+(b-l)+3+A);g>c&&(a.style.top=u(a.style.top)-(g-c)-3+A);k<e&&(a.style.left=u(a.style.left)+(e-k)+3+A);f>d&&(a.style.left=
u(a.style.left)-(f-d)-3+A)}function jc(a){for(var b=0,c=0;a&&"relative"!=ia(a).position&&ia(a).position!=ub;)b+=u(a.offsetTop),c+=u(a.offsetLeft),a=a.offsetParent;return{top:b,left:c}}function ia(a){return a.La=a.La||a.currentStyle||getComputedStyle(a,0)}function Jd(a){return function(){a&&a.parentNode&&a.parentNode.removeChild(a)}}function id(a){var b,c=jc(a),e=Id(a.src),d=e.size;if((e=e.url)&&e!=a.src){a.previousSibling&&"img"==a.previousSibling.nodeName.toLowerCase()?b=a.previousSibling:(b=a.cloneNode(!1),
xa&&b.detachEvent("onmouseover",hd),b.style.position=ub,b.style.top=Fb,b.style.left=Fb,b.style.margin=0+A,b.style.maxWidth="",b.style.maxHeight="",E(b,"mouseout",function(){clearTimeout(~~b.getAttribute("enlrgTmr"));Xa(b,"shrTmr",setTimeout(function(){kd(b,a)},10))}),a.parentNode.insertBefore(b,a));if(b.src==a.src){var f=b.cloneNode(!1);E(f,"load",function(){b.src=f.src;setTimeout(Jd(f),250)});f.src=e;b.parentNode.insertBefore(f,b)}b.width=a.width;b.height=a.height;b.style.top=c.top+A;b.style.left=
c.left+A;a.style.visibility="hidden";a.parentNode.style.zIndex=1E5;jd(b);b.setAttribute("enlrgTmr",setTimeout(function(){ld(b,d)},10))}}function kd(a,b){clearTimeout(~~a.getAttribute("enlrgTmr"));var c=jc(b),e=u(a.height)-10;a.width=u(a.width)-10;a.height=e;e=u(c.left)>u(a.style.left)?u(a.style.left)+5:u(a.style.left)-5;a.style.top=(u(c.top)>u(a.style.top)?u(a.style.top)+5:u(a.style.top)-5)+A;a.style.left=e+A;u(a.width)>u(b.width)?a.setAttribute("shrTmr",setTimeout(function(){kd(a,b)},10)):(a.style.top=
Fb,a.style.left=Fb,b.style.visibility="",b.parentNode.style.zIndex="")}function ld(a,b){clearTimeout(~~a.getAttribute("shrTmr"));var c=u(a.height)+10;a.width=u(a.width)+10;a.height=c;c=u(a.style.left)-5;a.style.top=u(a.style.top)-5+A;a.style.left=c+A;jd(a);u(a.width)<b&&a.setAttribute("enlrgTmr",setTimeout(function(){ld(a,b)},10))}function fc(){return"_lxretpopupignore"}function ed(a){var b=!1;if(!1===a)return b;try{b=null!==t.querySelector(a)}catch(c){}return b}function pc(a,b,c){Ra=!0;b&&(a?(t.write('<script type="text/javascript" language="JavaScript" src="'+
P+"luxupcdna.com/multishows/"+b+"/"+ta()+'">\x3c/script>'),Ra=!1):T(P+"luxupcdna.com/multishows/"+b+"/"+ta(b),function(){Ra=!1}));c&&(Gb&&clearInterval(Gb),Gb=setInterval(function(a){return function(){var b=(new Date).getTime(),c=!X.bidding;if(b>X.start+Hb&&b<X.start+Hb+100||c)Yc("Bidding:\n   started: "+(new Date(X.start)).toISOString()+"\n   ended: "+(new Date(X.end)).toISOString()),clearInterval(Gb),Ra=!0,T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(){Ra=!1})}}(c),50))}function Db(a){if(!Ra){var b=
fd(!0),c=b[0],b=b[1];if(!hb&&(c||b)&&!qc){var e=c.split(";"),d=b.split(";"),f=e.concat(d);z(f,function(a){~md.indexOf(f[a])&&f.splice(a,1)});if(f.length){md=f;qc=!0;rc=function(a,b,c){return function(d){d=d||[];qc=ib=!1;var e=[],f=[];z(b,function(a,b){~d.indexOf(""+b)||e.push(b)});z(c,function(a,b){~d.indexOf(""+b)||f.push(b)});pc(a,e.join(";"),f.join(";"))}}(a,e,d);Oa("getPreloadItems",{ids:f},Kd);ib=setTimeout(rc,100);return}}pc(a,c,b)}}var F=k,t=document,h=window,L=t.body,ba=t.documentElement,
ab=function(a){a=a||t;html=a.documentElement;var b=bb("head",!1,a);if(b)return b;for(b=html.firstChild;b&&"#text"==b.nodeName.toLowerCase();)b=b.nextSibling;if(b&&"#text"!=b.nodeName.toLowerCase())return b;a=H("head",a);html.appendChild(a);return a}(),ja=navigator.userAgent.toLowerCase(),Ld=(navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],Ka="CSS1Compat"===t.compatMode,Ab=/yabrowser/.test(ja),ad=/chrome/.test(ja)&&!Ab,Ya=ad||Ab,Ib=/opera/.test(ja),xa=/msie/.test(ja)&&
!Ib,Md=!window.ActiveXObject&&"ActiveXObject"in window,B=t.getElementsByClassName?function(a,b){return(b||document).getElementsByClassName(a)}:function(a,b){b=b||document;var c=b.getElementsByTagName("*"),e=c.length,d=a.split(/\s+/),f=d.length,h=[],g,l;for(g=0;g<e;g++)for(l=0;l<f;l++)if(~c[g].className.search("\\b"+d[l]+"\\b")){h.push(c[g]);break}return h},kc=Object.create;"function"!==typeof kc&&(kc=function(a){function b(){}b.prototype=a;return new b});var pb=u(f),y="__lxG"+pb+"__",Jb={},qa=!1,
Ra=!1,oc=null,Eb=0,Fa=[],Pa=null,cd=Ya?Fd():bd(),Mc="bottom",A="px",Fb="-100000"+A,ub="absolute",I={},Ub="type",Y="",nd=!1,Na="scroll",ea="click",eb="ios",R="android",vb=xa&&(!Ka||8>u(Ld)&&Ka),P="http"+("about:"==h.location.protocol?"https:"==h.top.location.protocol?"s":"":"https:"==h.location.protocol?"s":"")+"://",ec=P+"luxupcdna.com/real_show_log/?data=",Bb=!1,sc="__lx"+pb,Vb=sc+"_load_cnt",Ec=sc+"_load_tmr",Fc=sc+"_load_tmr_pre",od=!1,Gb=!1,Hb=3E3,dd=!0,tc=5,uc=null,lc=[],Ga=null,Qa=[],ca=
{get:function(a,b){var c;this.X(a)?(c=t.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"),c=decodeURIComponent(c)||(q(b)?b:null)):c=q(b)?b:null;return c},set:function(a,b,c,e,d,f){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var h="";if(c)switch(c.constructor){case Number:h=Infinity===c?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+c;break;case String:h="; expires="+c;break;case Date:h=
"; expires="+c.toUTCString()}t.cookie=encodeURIComponent(a)+"="+encodeURIComponent(b)+h+(d?"; domain="+d:"")+(e?"; path="+e:"")+(f?"; secure":"");return!0},Wa:function(a,b,c){if(!a||!this.Xa(a))return!1;t.cookie=encodeURIComponent(a)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(c?"; domain="+c:"")+(b?"; path="+b:"");return!0},X:function(a){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(t.cookie)},list:function(){for(var a=t.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,
"").split(/\s*(?:\=[^;]*)?;\s*/),b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);return a}};E(h,Na,Vc);Jb[y]={};Jb[y].sa=function(a){if(!Y)return!0;a=a||h.event;var b=(a.target||a.srcElement).nodeName.toLowerCase();if(xa&&"a"==b)return!0;Y+="?rnd="+Z()+(h[y].Ka?"&"+h[y].Ka:"");Ib?(h.open(Y,y+"popunder","resizable=1,toolbar=1,location=1,menubar=1,status=1,directories=0,width="+screen.availWidth+",height="+screen.availHeight),h.blur(),h.focus()):Ya?yd(Y,a):xa?Uc(Y):Md?zd(Y):setTimeout(function(){Uc(Y)},
0);Za(L,Ya||Ib?"mousedown":ea,Jb[y].sa);return!0};var hb=null;q(h[y])||(h[y]={});q(h[y].instances)||(h[y].instances=[]);q(h[y].blocks)||(h[y].blocks={});var X={bidding:!1,start:0,end:0,bids:!1},Sa=Z(),ka=y+Sa;h[ka]={};h[y].instances.push(Sa);q(h.__lxG__)||(h.__lxG__={});Hb=l(h.__lxG__.biddingBlocksDelay,Hb);q(h[y].closed)||(h[y].closed=function(){},h[y].clicked=function(){});q(h[y].popunderShow)||(h[y].popunderShow=!1);q(h[y].allLoaded)||(h[y].allLoaded=function(){});q(h[y].popunderAdd)||(h[y].popunderAdd=
"");q(h[y].multishowsAdd)||(h[y].multishowsAdd="");var pd=y,qd=y+"cache",vc=ka,rd=h.frameElement&&h.frameElement.id&&0===h.frameElement.id.indexOf("google_ads_iframe_"),zb=[vc,pd,qd],ya=[h.location.hostname],zb=zb||["postMessageApiPrefix"],ya=ya||[window.location.hostname],wd="sender"+Z(),gb=[],fb={},fa=[],sd=[];E(h,"message",function(a){a.data&&q(a.data.indexOf)&&0===a.data.indexOf("__")&&Yc("from "+a.origin.replace(/https?:\/\//img,""));if(a.data&&(~ya.indexOf(a.origin.replace(/https?:\/\//img,
""))||~ya.indexOf("*"))){if(!q(a.data.indexOf))return!1;var b=!1,c="";z(zb,function(d,e){if(0===a.data.indexOf(e+"|"))return c=e,b=!0,!1});if(!b)return!1;var e=null;try{e=JSON.parse(a.data.replace(c+"|",""))}catch(g){return!1}if(l(e.type)){if("subscribe"==e.type){var d=!1,f=Zc(l(e.subscriber.events,["*"])),h=l(e.subscriber.eventsParams,{});z(fa,function(b){if(fa[b].Ua===a.source)return d=!0,fa[b].o=Zc(fa[b].o.concat(f)),Bd(fa[b].K,h),!1});d||fa.push({ea:xb(a.source,a.origin,e.subscriber.prefix),o:f,
K:h})}"event"!=e.type||~sd.indexOf(l(e.rnd,0))||(sd.push(e.rnd),xd(a,e,c),e.broadcast&&Sb(e.event_type,e.event))}}});var Ja=xb(h.top,h.top===h.self?h.location.protocol+"//"+h.location.hostname:"*",pd),Kd=xb(h.top,h.top===h.self?h.location.protocol+"//"+h.location.hostname:"*",qd);va("renderOver",function(a){if(rd){var b=a.data[0],c=h.frameElement.parentNode.parentNode,e=c.parentNode,d=h.parent,f=d.document||d.contentDocument||d.contentWindow.document;wa(b.style);d=f.createElement("div");d.id=b.div_name;
Q(d,b.source,f);c.style.display="none";e.insertBefore(d,c);K(b,f);z(a.data,function(a,b){if("counters"==b.type)return K(b,f),!1})}else{if(b=mc(l(a.data[0].div_name),l(a.data[0].sub_id)))b.innerHTML="";setTimeout(function(){h[ka].parser(a.data)},0)}});va("renderBidderOver",function(a){var b=a.data[0],c=b.id,e=l(b.sub_id);if(!q(F["_"+(c+(e?"."+e:""))]))return!1;a=a.num;var d=Z();if(rd){var e=h.frameElement.parentNode.parentNode,f=h.parent,k=f.document||f.contentDocument||f.contentWindow.document;va("bidHtml",
function(a,b,c,e,f){return function(h){if(h.rnd==d){var k=l(a.sub_id),n=f.createElement("div");n.id=a.div_name;k&&n.setAttribute("data-cnt",k);k=b.getAttribute("style");Xa(b,"style",(k?k+";":"")+"display: none !important;");c.insertBefore(n,b);h.html&&!h.url?aa(n,h.html,h.w,h.h,f,!1,l(a.use_sandbox),e):!h.html&&h.url&&aa(n,h.url,h.w,h.h,f,!0,l(a.use_sandbox),e);K(a,f);z(h.data,function(a,b){if("counters"==b.type)return K(b,f),!1});return-1}}}(b,e,e.parentNode,f,k))}else va("bidHtml",function(a){return function(b){if(b.rnd==
d){var c=a.div_name,e;if(l(a.sub_id)){var f=l(a.sub_id),h=t.querySelectorAll("#"+c);z(h,function(a){if(h[a].getAttribute("data-cnt")==f)return e=h[a],!1})}else e=t.querySelector("#"+c);e.innerHTML="";b.html&&!b.url?aa(e,b.html,b.w,b.h,k):!b.html&&b.url&&aa(e,b.url,b.w,b.h,k,!0);K(a,k);z(b.data,function(a,b){if("counters"==b.type)return K(b,k),!1});return-1}}}(b));Oa("getBidHtml",{id:c,num:a,rnd:d},Ja)});va("codePing",function(a,b){Oa("codePong",{},b)});yb("subscribe",{subscriber:{prefix:vc,events:["renderOver",
"renderBidder","renderBidderOver"]}},Ja,!0);var Ea=null,ud=["cfg","params","get_area_size"],vd=["counters","iframe_counters"],gc=[];h[ka].addPreload=function(a){var b=[];z(a,function(a,e){F[a]=e;b.push(a.replace("_",""))});pc(0,b.join(";"),"")};va("getPreloadItems",function(a,b){if(!hb||!Ea)return!1;var c=a.ids,e=!1,d=JSON.parse(JSON.stringify(gc)),f=[];z(c,function(a,b){l(Ea[b])&&(e=!0,d.push(Ea[b]),f.push(b))});e&&(z(f,function(a,b){delete Ea[b]}),Oa("preloadItems",{preloadItems:d,found:f},b))});
h[ka].parser=h[y].parser=function(a){Fa=[];var b=!1,c={},e={},d;for(d in a)a.hasOwnProperty(d)&&(g=a[d],l(g.sub_id)&&(b=!0),"params"==g.type?(c=l(g.site,{}),e=l(g.blocks,[]),l(c.ch_dmn)&&(~ya.indexOf(c.ch_dmn)||ya.push(c.ch_dmn)),z(e,function(a,b){q(b.ch_dmn)&&!~ya.indexOf(b.ch_dmn)&&ya.push(b.ch_dmn)})):"cfg"==g.type&&(od=l(g.isMobile)&&ga())&&tc&&!uc&&(uc=setInterval(function(){return function(){tc?(tc--,r()):clearInterval(uc)}}(),3E3)));var f=!1;z(a,function(b){var c=a[b];if(l(c.id)){var d=l(c.sub_id);
b="_"+c.id;c=d?"_"+c.id+"."+d:!1;if(1==l((c?l(F[c]):l(F[b])).preload))f=!0;else return f=!1}});for(var k in a)if(a.hasOwnProperty(k)){var g=a[k];if("params"!=g.type&&"cfg"!=g.type)if(!f&&"counters"==g.type){if(g.hasOwnProperty("urls"))for(var x=0;x<g.urls.length;x++)H("img").src=g.urls[x]+"&_lxrnd_="+Z()}else if(!f&&"iframe_counters"==g.type){if(g.hasOwnProperty("sources"))for(x=0;x<g.sources.length;x++)c=g.sources[x],d=H("iframe"),d.id="__lxG__frame_tracker_"+x,d.sandbox="allow-same-origin allow-scripts allow-forms",
d.style.width=1+A,d.style.height=1+A,d.setAttribute("allowtransparency","true"),d.setAttribute("marginwidth","0"),d.setAttribute("marginheight","0"),d.setAttribute("hspace","0"),d.setAttribute("vspace","0"),d.setAttribute("frameborder","0"),d.setAttribute("scrolling","no"),d.src="javascript:'"+(c+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")+"'",L.appendChild(d)}else if(f||"get_area_size"!=g.type){if("mdcheck"==g.type)return g.hasOwnProperty("url")&&T(P+g.url+(~g.url.indexOf("?")?"&":"?")+
"f="+ka),!0;if("mdparam"==g.type)return g.hasOwnProperty("param")&&(Bb=g.param,g.hasOwnProperty("alg")&&g.alg&&(ec=P+g.alg+".luxupcdna.com/real_show_log/?data="),b=l(g.incoming_params),k=l(g.incoming_ids),b&&k?(b+="&md="+encodeURIComponent(Bb),b=b.replace(/(^rt=)\d+?(&)/mg,"$1"+Z()+"$2"),setTimeout(function(a,b){return function(){Hc(a,b)}}(k,b),0)):setTimeout(function(){Db(0)},0)),!0;if(!f&&l(g.id)&&(c=l(g.sub_id),d="_"+g.id,x=c?"_"+g.id+"."+c:!1,!(!x&&q(h[y].blocks[d])&&h[y].blocks[d]!=Sa||x&&
q(h[y].blocks[x])&&h[y].blocks[x]!=Sa))){q(h[y].blocks[d])||(h[y].blocks[d]=Sa);var m=x?l(F[x]):l(F[d]);if(!m)q(e[g.id])?m=e[g.id]:m={},F[x?x:d]=m;else if(q(e[g.id])){var D=["refresh_limit"];z(e[g.id],function(a){~D.indexOf(a)&&q(m[a])||(m[a]=e[g.id][a])})}if(q(m.debug)&&m.debug&&(d=!1,t.location.search?(x=Cd(t.location.search),q(x.lx_debugmode)&&1==x.lx_debugmode||(d=!0)):d=!0,d))continue;if(!q(m.location)&&t.getElementById(m.id)&&!t.getElementById(g.div_name)){d=t.querySelectorAll("#"+m.id);for(var J in d)d.hasOwnProperty(J)&&
"length"!=J&&d[J].setAttribute("id",g.div_name)}m.id=g.div_name;q(m.location)||t.getElementById(m.id)||(d=document.createElement("div"),d.setAttribute("id",m.id),L.appendChild(d));if(q(m)&&q(g.source)){d=mc(m.id,c);!1===Da&&(Da=q(g.isTablet)?u(g.isTablet):0);if(d&&"html"==g.type&&"exit"!=l(m.type)&&"native"!=l(m.type)&&g.source){qa||(wa(g.style),E(d,"click",Cb));d.innerHTML=g.source;m.C=!0;var G=cc(d);m.wa=G;q(g.real_show_log)&&g.real_show_log&&Fa.push([d,g.real_show_log]);if(l(G.lxm_responsive)){var B=
d.querySelectorAll(".lx_anons"),x=0,x=function(a,b){return function(){Xc(a,l(b.lxm_fit_factor,1.5),{min:l(b.lxm_fit_min,14)+A,max:l(b.lxm_fit_max,20)+A});z(a,function(a,c){Wc(c,{clamp:l(b.lxm_clamp)})})}}(B,G);setTimeout(x,50);setTimeout(x,250);setTimeout(x,500);setTimeout(x,1E3);setTimeout(x,2E3)}if(q(m.zoomImages)&&m.zoomImages)for(x=d.getElementsByTagName("img"),G=x.length,B=0;B<G;B++)t.addEventListener?x[B].addEventListener("mouseover",function(){id(this)},!1):x[B].attachEvent("onmouseover",hd);
K(g);oa(m,c)}d&&"exit"==l(m.type)&&g.source&&(d.style.display="none",qa||(wa(g.style),E(d,"click",Cb)),d.innerHTML=g.source,G=cc(d),m.wa=G,B=d.querySelectorAll(".lx_anons"),x=0,x=function(a,b){return function(){Xc(a,l(b.lxm_fit_factor,1.5),{min:l(b.lxm_fit_min,14)+A,max:l(b.lxm_fit_max,20)+A});z(a,function(a,c){Wc(c,{clamp:l(b.lxm_clamp)})})}}(B,G),setTimeout(x,1E3),za(g,m,d));d&&"pu"==g.type&&!nd&&(g.hasOwnProperty("url")?Y=g.url:Y=P+"s.luxupcdna.com/pu/"+g.id+".html",g.hasOwnProperty("pattern")&&
g.hasOwnProperty("timeout")?(x=ca.get(Ec,0),(new Date).getTime()-x>6E4*g.timeout&&da(1),x=u(ca.get(Vb,0)),~g.pattern.indexOf(x)||~g.pattern.indexOf(7)&&7<=x||(Y=!1)):Y=!1,Y&&(E(L,Ya||Ib?"mousedown":"click",Jb[y].sa),m.C=!0),nd=!0);if(("js"==g.type||"iframe"==g.type&&"js_npm"==l(m.type))&&"native"!=l(m.type)&&(x=!1,G=l(m.ai_mode),m.P=od&&!l(g.mobATF)&&!l(g.isTablet),"js_npm"==l(m.type)&&l(m.check)&&l(m.location)&&!c&&(d&&(x=d.getAttribute("data-cnt")?d.getAttribute("data-cnt"):1,d.parentNode.removeChild(d)),
G?(d=ed(m.check),d||(m.R=l(m.R,0),10>m.R&&(m.R||(m.Na=function(a,b,c){return function(){a[b].parser([c])}}(h,ka,g)),setTimeout(m.Na,1E3),m.R++))):d=nc(m)),d)){qa||(q(g.style)&&wa(g.style),G||E(d,"click",Cb));!c&&l(m.add_meta)&&Aa("width=device-width,initial-scale=1.0,maximum-scale=2.0,user-scalable=1");if(G&&!c){if(G=!q(m.c))m.c={H:!1,m:null,F:null,I:[]};m.c.source=g.source;m.c.Oa=g.type;m.c.ma=l(m.inject_pre_process);m.c.qa=l(g.pre_source);m.c.width=l(g.width);m.c.height=l(g.height);m.c.Pa=l(g.use_sandbox);
m.c.counters=l(g.counters,[]);m.c.id=g.id;if(G)C(m,!1,x),m.c.ra=function(a){return function(){!a.c.H&&Ha(a)&&C(a);h.innerHeight+h.scrollY>=(ba&&ba.scrollHeight||L.scrollHeight)&&Za(window,"scroll",a.c.ra)}}(m),E(window,"scroll",m.c.ra);else if(d=mc(m.id,c))m.P&&ha()>Ba(d).top?(x=p(d,g.source))?(Q(d,x),K(g),oa(m,c),v(d,{id:g.id,type:"npm_resized"})):v(d,{id:g.id,type:"npm"}):("iframe"==g.type?(q(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0))):Q(d,g.source),
K(g),oa(m,c));!l(m.ai_clone_source)&&m.c.m.length&&Ha(m)&&(m.c.source=!1,C(m,!0))}else if(!l(m.ai_clone_source)&&(m.P&&ha()>Ba(d).top?(x=p(d,g.source))?(Q(d,x),K(g),oa(m,c),v(d,{id:g.id,type:"npm_resized"})):v(d,{id:g.id,type:"npm"}):("iframe"==g.type?(q(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0))):Q(d,g.source),K(g),oa(m,c)),G=t.querySelectorAll("#"+m.id),!c&&(!b||l(m.location))&&G&&1<G.length))for(B=G.length;B;)d=G[B-1],1<G[B-1].getAttribute("data-cnt")&&
(m.P&&ha()>Ba(d).top?(x=p(d,g.source))?(Q(d,x),K(g),oa(m,c),v(d,{id:g.id,type:"npm_resized"})):v(d,{id:g.id,type:"npm"}):("iframe"==g.type?(q(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0))):Q(d,g.source),K(g),oa(m,c))),B--;m.C=!0}"js"!=g.type&&"iframe"!=g.type&&"html"!=g.type||"native"!=l(m.type)||(l(m.check)&&l(m.location)&&(d&&d.parentNode.removeChild(d),d=nc(m,!0)),d&&(qa||q(g.style)&&wa(g.style),"iframe"==g.type?(q(g.pre_source)&&Q(d,g.pre_source),aa(d,
g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0))):Q(d,g.source),K(g),m.C=!0));if("iframe"==g.type&&"js_npm"!=l(m.type)){if(l(m.check)||l(m.location))d&&d.parentNode.removeChild(d),d=nc(m);qa||q(g.style)&&wa(g.style);q(g.pre_source)&&Q(d,g.pre_source);if(d){aa(d,g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0));K(g);oa(m,c);G=t.querySelectorAll("#"+m.id);if((!b||l(m.location))&&G&&1<G.length)for(B=G.length;B;)d=G[B-1],1<G[B-1].getAttribute("data-cnt")&&(q(g.pre_source)&&Q(d,g.pre_source),aa(d,
g.source,g.width,g.height,t,!1,l(g.use_sandbox,!0)),K(g),oa(m,c)),B--;m.C=!0}}d&&"float"==g.type&&(x=!1,qa||(wa(g.style),E(d,ea,Cb)),c=g.id,q(I[c])||(I[c]=F["_"+c],I[c].N=c,I[c].a=d,I[c].B=!1,I[c].G=!1,I[c].O=!1,I[c].l=0,I[c].u=!1,I[c].aa=!1,I[c].ba=!1,I[c].L=!1,q(g.real_show_log)&&g.real_show_log&&(I[c].aa=!0,I[c].ba=g.real_show_log),x=!0),I[c].a.innerHTML=g.source,I[c].a.style[I[c].side]=-1E3+A,I[c].a.style.display="block",I[c].width=u(I[c].a.width?I[c].a.width:I[c].a.offsetWidth),I[c].a.style[I[c].side]=
-I[c].width+A,Pb(I[c],x),I[c].u&&(I[c].u=!1),Rc(I[c])(),m.C=!0,K(g));d&&"mobile"==g.type&&(G=!1,qa||wa(g.style),c=g.id,q(W[c])||(W[c]=F["_"+c],W[c].N=c,W[c].a=d,W[c].G=!1,W[c].l=0,W[c].u=!1,G=!0),d.innerHTML=g.source,m.C=!0,Lb(W[c],G),W[c].u&&(W[c].u=!1),K(g));g.hasOwnProperty("iframe_source")&&(aa(d,g.iframe_source,1,1),K(g));"inlinevideo"==g.type&&sa(t.querySelector(l(m.location)),{Sa:g.video_url,ia:g.click_url,Ra:g.video_start_url,ua:g.video_end_url,J:l(g.video_trackers,!1),Ta:g.width,Qa:g.height,
pa:l(g.overlay_html,""),ja:l(g.full_view_percent,100),V:l(m.width),ya:l(m.style),Ba:l(m.hideClose),Ca:l(m.hideMarker),ka:l(m.hidePostblock)})}}}else if(g.hasOwnProperty("ids"))for(c=0;c<g.ids.length;c++)d=g.ids[c],q(F["_"+d])&&setTimeout(Hd(d,t.getElementById(F["_"+d].id)),3E3)}if(f){var N=[];z(a,function(b){b=a[b];if(l(b.id)){var c=l(b.sub_id),d="_"+b.id,c=c?"_"+b.id+"."+c:!1;1==l((c?l(F[c]):l(F[d])).preload)&&N.push(b)}else N.push(b)});Qb(a);return!0}for(var Ma in F)F.hasOwnProperty(Ma)&&!q(F[Ma].C)&&
q(F[Ma].cap)&&F[Ma].cap();qa=!1;setTimeout(function(){h[y].allLoaded()},0);Vc()};var gd=[],ea="click",Na="scroll",R="android",eb="ios",Mc="bottom",ub="absolute",W={},Nc=!1,rb=!1,sb=!1,Da=!1,Zb=1,Ic=1,Jc=1,bc=0,ac=0,$b=!1,qb=-1,A="px",Wb=!1,Cc=!1,La=[],na=[],$a=[],qc=!1,md=[],rc=!1,ib=!1;va("preloadItems",function(a){ib&&(clearTimeout(ib),ib=!1,setTimeout(function(){h[ka].parser(a.preloadItems)},0),setTimeout(function(){rc(a.found)},0))});da(u(ca.get(Vb,0))+1);(function(){var a=!1;q(h.__lxG__.multishows_params)&&
q(h.__lxG__.multishows_params.singleton)&&(a=h.__lxG__.multishows_params.singleton);z(F,function(b){var c=!1;a&&a!=b.replace("_","")&&(c=!0);var f=t.getElementById(F[b].id);!0===l(F[b].preload)?(f=!0,null===hb&&(hb=!0)):hb=!1;c||"float"!=l(F[b].type)||ca.X(fc())&&(c=!0);!f||c?delete F[b]:Eb+=1});var b=ca.list(),c;for(c in b)b.hasOwnProperty(c)&&0===b[c].indexOf("_lxblockignore_")&&lc.push(b[c].replace("_lxblockignore_",""));Eb&&z(F,function(a){a in h[y].blocks?delete F[a]:!0!==l(F[a].preload)&&(h[y].blocks[a]=
Sa)})})();var wc=[];z(F,function(a){wc.push(a.replace("_",""))});va("bids",function(a){X=a});yb("subscribe",{subscriber:{prefix:vc,events:["bids"],eventsParams:{bids:{ids:wc}}}},Ja,!0);yc("getBids",{ids:wc},Ja,function(a){X=a;Db(0)},function(){Db(0)});return ka}var da=document,p=window,jb=document,Kb=window;(function(f){f=f||jb;html=f.documentElement;var k;k=f||jb;if(k=k.getElementsByTagName("head")[0])return k;for(k=html.firstChild;k&&"#text"==k.nodeName.toLowerCase();)k=k.nextSibling;if(k&&"#text"!=
k.nodeName.toLowerCase())return k;f=f||jb;f=f.createElement("head");html.appendChild(f);return f})();var Ob=navigator.userAgent.toLowerCase();navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/);var Va=Object.create;"function"!==typeof Va&&(Va=function(f){function k(){}k.prototype=f;return new k});p.__lxGc__=p.__lxGc__||{s:{},b:0};p.__lxGp__=p.__lxGp__||{s:{}};if(p.__lxGc__.f)return setTimeout(p.__lxGc__.f,0),!1;var sa=["__lxGc__"],ga=[window.location.hostname],sa=sa||["postMessageApiPrefix"],
ga=ga||[window.location.hostname],Nb="sender"+Ia(),Aa=[],za={},O=[],kb=[];(function(f,k,r){if(f){"[object NodeList]"!=Object.prototype.toString.call(f)&&(f=[f]);k=k.split(" ");var p=k.length,ra;for(ra=0;ra<p;ra++)C(f,function(){this.addEventListener?this.addEventListener(k[ra],r,!1):this.attachEvent("on"+k[ra],r)})}})(Kb,"message",function(f){f.data&&U(f.data.indexOf)&&0===f.data.indexOf("__")&&Rb("from "+f.origin.replace(/https?:\/\//img,""));if(f.data&&(~ga.indexOf(f.origin.replace(/https?:\/\//img,
""))||~ga.indexOf("*"))){if(!U(f.data.indexOf))return!1;var k=!1,r="";C(sa,function(p,v){if(0===f.data.indexOf(v+"|"))return r=v,k=!0,!1});if(!k)return!1;var p=null;try{p=JSON.parse(f.data.replace(r+"|",""))}catch(Ha){return!1}if(M(p.type)){if("subscribe"==p.type){var ra=!1,D=Ua(M(p.subscriber.events,["*"])),S=M(p.subscriber.eventsParams,{});C(O,function(k){if(O[k].Ua===f.source)return ra=!0,O[k].o=Ua(O[k].o.concat(D)),Sb(O[k].K,S),!1});ra||O.push({ea:Ta(f.source,f.origin,p.subscriber.prefix),o:D,
K:S})}"event"!=p.type||~kb.indexOf(M(p.rnd,0))||(kb.push(p.rnd),Qb(f,p,r),p.broadcast&&Pb(p.event_type,p.event))}}});var lb={},mb={};p.__lxGc__.f=function(){if(!U(da.body)||!da.body)return!1;C(p.__lxGp__.s,function(f){var r=M(p.__lxGp__.s[f].b,[]);if(r.length){r=S(r);p.__lxGp__.s[f].b=[];var v={};C(r,function(f){f=r[f];var k;k=U(mb[f])?++mb[f]:1;mb[f]=k;v[1<k?f+"."+k:f]={preload:!0}});M(lb[f])?p[lb[f]].addPreload(v):lb[f]=Wa(f.replace("_",""),v)}});if(p.__lxGc__.b&&p.__lxGc__.b!==p.__lxGc__["b`"]){p.__lxGc__["b`"]=
p.__lxGc__.b;p.__lxGc__["s`"]?C(p.__lxGc__.s,function(f){p.__lxGc__["s`"][f]?C(p.__lxGc__.s[f].b,function(r){p.__lxGc__["s`"][f].b[r]?(p.__lxGc__["s`"][f].b[r].i=p.__lxGc__.s[f].b[r].i,p.__lxGc__["s`"][f].b[r].ver=p.__lxGc__["s`"][f].b[r].ver||0,p.__lxGc__["s`"][f].b[r].ver++):(p.__lxGc__["s`"][f].b[r]=S(p.__lxGc__.s[f].b[r]),p.__lxGc__["s`"][f].b[r].ver=0)}):p.__lxGc__["s`"][f]=S(p.__lxGc__.s[f])}):p.__lxGc__["s`"]=S(p.__lxGc__.s);var f=da.querySelectorAll(".__lxGc__");if(!f.length)return!1;C(p.__lxGc__["s`"],
function(k){var r=0,v={},O={},D="__lxG"+k.replace("_","")+"__",M=Ta(Kb.top,"*",D);~sa.indexOf(D)&&sa.push(D);C(p.__lxGc__["s`"][k].b,function(D){var N=p.__lxGc__["s`"][k].b[D];if(!N._d||U(N.cnt)&&N.cnt!=N.i+1){p.__lxGc__["s`"][k].b[D]._d=!0;N.id=N.id||"lx"+D;N.cnt=N.cnt||0;var M=new RegExp("\\[(?:'|\")b(?:'|\")\\]\\[(?:'|\")"+D+"(?:'|\")\\]","im");C(f,function(k){if((M.test(f[k].text)||"div"===f[k].nodeName.toLowerCase()&&f[k].nextElementSibling&&"script"===f[k].nextElementSibling.nodeName.toLowerCase()&&
M.test(f[k].nextElementSibling.text)||"div"===f[k].nodeName.toLowerCase()&&f[k].getElementsByTagName("script").length&&M.test(f[k].getElementsByTagName("script")[0].text))&&!f[k].getAttribute("data-cnt")){f[k].setAttribute("data-cnt",++N.cnt);var p=document.createElement("div");p.setAttribute("id",N.id);p.setAttribute("data-cnt",N.cnt);p.className="__lxG__multi __lxG__multi_"+N.id;f[k].parentNode.insertBefore(p,f[k]);var C=1==N.cnt?D:D+"."+N.cnt;v[C]=N;O[C]={anchor:f[k],A:p};r++}})}});if(r){var D=
k.replace("_",""),da=S(p.__lxGc__["s`"][k]),la=S(v),ga=[];C(la,function(f){ga.push(f)});Lb({ids:ga},M,function(f,k,p){return function(k){var r=k.ids,v={};C(p,function(f){var k=S(p[f]);C(r,function(p,r){var v=r.old,D="_"+r["new"],C=r.cnt;if(v==f)return f=D,k.cnt=C,O[v].anchor.setAttribute("data-cnt",C),O[v].A.setAttribute("data-cnt",C),!1});v[f]=k});setTimeout(function(){Wa(f,v)},0)}}(D,da,la),function(f,k,p){return function(){Wa(f,p)}}(D,da,la))}})}};p.__lxGc__.f();"complete"!==da.readyState&&(p.__lxGc__.t=
setInterval(p.__lxGc__.f,10),da.addEventListener("readystatechange",function(){"complete"==da.readyState&&(clearInterval(p.__lxGc__.t),delete p.__lxGc__.t,p.__lxGc__.f())},!1))})();
