(function(g){var window=this;var ara=function(a,b){var c=[];g.zf(b,function(a){var b;try{b=g.Ri.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.p(b)?g.Qi(b)&&c.push(a):c.push(a)},a);
return c},bra=function(a,b){var c=ara(a,b);
(0,g.H)(c,function(a){g.Ri.prototype.remove.call(this,a)},a)},W8=function(a){return a.H?a.F+((0,g.G)()-a.A)/1E3:a.F},cra=function(){var a=g.Si;
bra(a,a.g.rd(!0))},X8=function(a){g.Hz.call(this,"ScreenServiceProxy");
this.Ic=a;this.o=[];this.o.push(this.Ic.$_s("screenChange",(0,g.z)(this.EJ,this)));this.o.push(this.Ic.$_s("onlineScreenChange",(0,g.z)(this.pG,this)))},Y8=function(a){g.Dz("cloudview",a)},Z8=function(a){Y8("setApiReady_ "+a);
g.ka("yt.mdx.remote.cloudview.apiReady_",a,void 0)},$8=function(){return g.u("yt.mdx.remote.cloudview.instance_")},a9=function(a){g.wi[a]&&(a=g.wi[a],(0,g.H)(a,function(a){g.ui[a]&&delete g.ui[a]}),a.length=0)},b9=function(){return g.u("yt.mdx.remote.connection_")},c9=function(a){g.ka("yt.mdx.remote.connectData_",a,void 0)},d9=function(a){g.ka("yt.mdx.remote.currentScreenId_",a,void 0)},e9=function(){return g.u("yt.mdx.remote.currentScreenId_")},g9=function(){if(!f9){var a=g.u("yt.mdx.remote.screenService_");
f9=a?new X8(a):null}return f9},h9=function(a){g.ka("yt.mdx.remote.cloudview.initializing_",a,void 0)},i9=function(){return!!g.u("yt.mdx.remote.cloudview.apiReady_")},j9=function(a){Y8("setCastInstalled_ "+a);
g.Ui("yt-remote-cast-installed",a)},k9=function(a){g.Dz("cloudview",a)},dra=function(a,b){$8().init(a,b)},l9=function(){return!!g.Vi("yt-remote-cast-installed")},n9=function(){Y8("dispose");
var a=$8();a&&a.dispose();g.ka("yt.mdx.remote.cloudview.instance_",null,void 0);Z8(!1);g.yi(m9);m9.length=0},era=function(){var a=window.document.createElement("a");
g.se(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Na(a)},fra=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},gra=function(a){var b=g.si();
if(b)if(b.clear(a),a)a9(a);else for(var c in g.wi)a9(c)},o9=function(a,b){g.vi[a]=!0;
var c=g.si();c&&c.publish.apply(c,arguments);g.vi[a]=!1},p9=function(a){return a?a.dataset?a.dataset[g.bh("loaded")]:a.getAttribute("data-loaded"):null},q9=function(){return g.u("yt.mdx.remote.channelParams_")||{}},s9=function(a){var b=b9();
c9(null);a||d9("");g.ka("yt.mdx.remote.connection_",a,void 0);r9&&((0,g.H)(r9,function(b){b(a)}),r9.length=0);
b&&!a?o9("yt-remote-connection-change",!1):!b&&a&&o9("yt-remote-connection-change",!0)},t9=function(){return g.u("yt.mdx.remote.connectData_")},u9=function(){var a=e9();
if(!a)return null;var b=g9().ud();return g.ci(b,a)},v9=function(a,b){j9(!0);
h9(!1);dra(a,function(a){a?(Z8(!0),g.Ai("yt-remote-cast2-api-ready")):(k9("Failed to initialize cast API."),j9(!1),g.Wi("yt-remote-cast-available"),g.Wi("yt-remote-cast-receiver"),n9());b(a)})},w9=function(){return l9()?$8()?$8().getCastSession():(k9("getCastSelector: Cast is not initialized."),null):(k9("getCastSelector: Cast API is not installed!"),null)},x9=function(){if(g.Zpa){var a=2,b=g.sz(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.xz("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.uz,c)}},hra=function(){var a=era(),b=window.document.getElementById(a),c=b&&p9(b);
c||b&&!c||(b=fra(a,function(){p9(b)||(g.ch(b,"loaded","true"),g.Ai(a),g.Qg(g.B(gra,a),0))}))},ira=function(a){return(0,g.R)(a,function(a){return{key:a.id,
name:a.name}})},z9=function(a,b){e9();
u9()&&u9();d9(a.id);var c=new g.TB(y9,a,q9());c.connect(b,t9());c.subscribe("beforeDisconnect",function(a){o9("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){b9()&&(b9(),s9(null))});
s9(c)},A9=function(){var a=g.Zi();
if(!a)return null;var b=g9().ud();return g.ci(b,a)},B9=function(a){g.Dz("remote",a)},C9=function(){var a=b9();
return!!a&&3!=a.getProxyState()},D9=function(){i9()?$8().stopSession():k9("stopSession called before API ready.");
var a=b9();a&&(a.disconnect(1),s9(null))},E9=function(){var a;
a=g9().Ic.$_gos();var b=u9();b&&b9()&&(g.bi(a,b)||a.push(b));return ira(a)},H9=function(a,b){g.Bn.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.HB;this.A=this.o=null;this.H=(0,g.z)(this.JE,this);this.F=(0,g.z)(this.Hi,this);this.G=(0,g.z)(this.IE,this);this.J=(0,g.z)(this.SE,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Bp,this),F9(this))):c=3;0!=c&&(b?this.Bp(c):g.Qg((0,g.z)(function(){this.Bp(c)},this),0));
var d=w9();d&&G9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},I9=function(a){return new g.MB(a.B.getPlayerContextData())},L9=function(a,b,c,d,e){var f=I9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.RB(f,b,d);g.p(c)&&(g.PB(f,c),l.currentTime=c);g.p(k)&&(l.listId=k);J9(a,"setPlaylist",l);e||K9(a,f)},F9=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.B(this.JG,a),this))},a)},M9=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},N9=function(a,b){50>a.C.xc()&&g.JB(a.C,b)},O9=function(a,b,c){var d=I9(a);
g.PB(d,c);-1E3!=d.g&&(d.g=b);K9(a,d)},J9=function(a,b,c){a.B.sendMessage(b,c)},K9=function(a,b){M9(a);
a.B.setPlayerContextData(g.SB(b));F9(a)},G9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Hi(null));
a.A=b;a.A&&(P9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Hi(a.A.media[0]))},Q9=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=I9(a);b.contentId!=d.videoId&&P9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.PB(d,a.o.getEstimatedTime());K9(a,d)}else P9("No cast media video. Ignoring state update.")},P9=function(a){g.Dz("CP",a)},jra=function(a){var b=!1;
$8()||(a=new g.hA(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Ui("yt-remote-cast-available",a);o9("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){Y8("onReceiverSelected: "+a.friendlyName);
g.Ui("yt-remote-cast-receiver",a);o9("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){Y8("onReceiverResumed: "+a.friendlyName);
g.Ui("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){Y8("onSessionChange: "+g.Zh(a));
a||g.Wi("yt-remote-cast-receiver");o9("yt-remote-cast2-session-change",a)}),g.ka("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
Y8("cloudview.createSingleton_: "+b);return b},kra=function(){var a=0<=g.dc.search(/\ (CrMo|Chrome|CriOS)\//);
return g.oi||a},R9=function(a,b){i9()?$8().setConnectedScreenStatus(a,b):k9("setConnectedScreenStatus called before ready.")},S9=function(){Y8("clearCurrentReceiver");
g.Wi("yt-remote-cast-receiver")},lra=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){x9();a({command:"cast.sender.init"});return}}if(window.chrome)if(x9(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.qz();55<=b?a="55":50<=b&&(a="50");g.xz("//www.gstatic.com/eureka/clank"+a+g.vz,g.uz)}else g.yz(0);else g.uz()},mra=function(a){a?(g.Ui("yt-remote-session-app",a.app),g.Ui("yt-remote-session-name",a.name)):(g.Wi("yt-remote-session-app"),g.Wi("yt-remote-session-name"));
g.ka("yt.mdx.remote.channelParams_",a,void 0)},nra=function(){var a=q9();
if(g.Sb(a)){var a=g.Yi(),b=g.Vi("yt-remote-session-name")||"",c=g.Vi("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.ka("yt.mdx.remote.channelParams_",a,void 0)}},ora=function(){var a=A9();
a?(B9("Resume connection to: "+g.Zh(a)),z9(a,0)):(g.hj(),S9(),B9("Skipping connecting because no session screen found."))},pra=function(a){B9("remote.onCastSessionChange_: "+g.Zh(a));
if(a){var b=u9();b&&b.id==a.id?R9(b.id,"YouTube TV"):(b&&D9(),z9(a,1))}else b9()&&D9()},qra=function(){var a=E9(),b=u9();
b||(b=A9());return g.Wa(a,function(a){return b&&g.Wh(b,a.key)?!0:!1})},T9=function(){var a=g.Vi("yt-remote-cast-receiver");
return a?a.friendlyName:null},rra=function(a,b,c,d){kra()?jra(b)&&(h9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?v9(a,c):(window.__onGCastApiAvailable=function(b,d){b?v9(a,c):(k9("Failed to load cast API: "+d),j9(!1),h9(!1),g.Wi("yt-remote-cast-available"),g.Wi("yt-remote-cast-receiver"),n9(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):hra():lra())):Y8("Cannot initialize because not running Chrome")},U9=
function(a){this.B=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Lf(a)||"";b&&(this.B=":"+b);this.A=g.Kf(a)||"";a=g.dc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ma(a,"10.0")&&(this.o=!1))},V9=function(a,b,c){g.L.call(this);
this.H=a;this.Z=b;b.addEventListener("onVolumeChange",this.Pk,this);b.addEventListener("onCaptionsTrackListChanged",this.Ku,this);b.addEventListener("captionschanged",this.zu,this);b.addEventListener("captionssettingschanged",this.Zo,this);b.addEventListener("videoplayerreset",this.Ki,this);b.addEventListener("mdxautoplaycancel",this.Ir,this);this.A=!1;this.g=c;c.isDisposed();c.subscribe("proxyStateChange",this.Xu,this);c.subscribe("remotePlayerChange",this.Ji,this);c.subscribe("remoteQueueChange",
this.Ki,this);c.subscribe("autoplayUpNext",this.xu,this);c.subscribe("previousNextChange",this.Uu,this);c.subscribe("nowAutoplaying",this.Nu,this);c.subscribe("autoplayDismissed",this.wu,this);this.suggestion=null;this.D=new g.jl(64);this.C=this.B=window.NaN;this.o={};this.G=new g.Hd(this.mw,1E3,this);g.M(this,this.G);this.F=new g.Or(this.fM,1E3,this);g.M(this,this.F);this.J=g.v;this.Zo();this.Ki();this.Ji()},W9=function(a,b){var c=a.H,d=a.Z.getVideoData().lengthSeconds;
c.H=b||0;c.g.Qa("progresssync",b,d)},Z9=function(a){W9(a,0);
X9(a);Y9(a,new g.jl(64))},b$=function(a,b){if($9(a)&&!a.A){var c=null;
b&&(c={style:a.Z.jj()},g.Yb(c,b));a.g.Vv(a$(a),c);a.o=I9(a.g).o}},c$=function(a,b){var c=a.Z.je();
c?L9(a.g,a$(a),b,c.g,c.listId.toString()):L9(a.g,a$(a),b);Y9(a,new g.jl(1))},d$=function(a,b){if(b){var c=a.Z.Ec("captions","tracklist",{Ut:1});
c&&c.length?(a.Z.$e("captions","track",b),a.A=!1):(a.Z.Fp("captions"),a.A=!0)}else a.Z.$e("captions","track",{})},$9=function(a){return I9(a.g).videoId==a$(a)},a$=function(a){return a.Z.getVideoData().videoId},e$=function(a){X9(a);
if(!a.g.isDisposed()){var b=I9(a.g);b.gb()&&Y9(a,new g.jl(8));W9(a,g.QB(b));a.B=g.Qg((0,g.z)(function(){e$(this)},a),500)}},X9=function(a){g.Sg(a.B);
a.B=window.NaN},f$=function(a){g.Sg(a.C);
a.C=window.NaN},Y9=function(a,b){f$(a);
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.T(b,2);if(d!=g.T(a.D,2)){var e=a.Z;(e=g.Il(e.app,e.playerType||1))&&g.yX(e,d)}a.D=b;g$(a.H,c,b)}},h$=function(){var a=qra();
!a&&l9()&&T9()&&(a={key:"cast-selector-receiver",name:T9()});return a},sra=function(){var a=E9();
l9()&&g.Vi("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},tra=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.Si&&cra();g.aj();y9||(y9=new U9,g.jj()&&(y9.g="/api/loungedev"));r9||(r9=g.u("yt.mdx.remote.deferredProxies_")||[],g.ka("yt.mdx.remote.deferredProxies_",r9,void 0));nra();var c=g9();if(!c){var d=new g.Uz(y9);g.ka("yt.mdx.remote.screenService_",d,void 0);c=g9();rra(a,d,function(a){a?e9()&&R9(e9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){o9("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.u("yt.mdx.remote.initialized_")&&
(g.ka("yt.mdx.remote.initialized_",!0,void 0),B9("Initializing: "+g.lf(b)),i$.push(g.xi("yt-remote-cast2-availability-change",function(){o9("yt-remote-receiver-availability-change")})),i$.push(g.xi("yt-remote-cast2-receiver-selected",function(){c9(null);
o9("yt-remote-auto-connect","cast-selector-receiver")})),i$.push(g.xi("yt-remote-cast2-receiver-resumed",function(){o9("yt-remote-receiver-resumed","cast-selector-receiver")})),i$.push(g.xi("yt-remote-cast2-session-change",pra)),i$.push(g.xi("yt-remote-connection-change",function(a){a?R9(e9(),"YouTube TV"):A9()||(R9(null,null),S9())})),a=q9(),b.isAuto&&(a.id+="#dial"),g.zm("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,B9(" -- with channel params: "+g.lf(a)),mra(a),
c.start(),e9()||ora())},j$=function(){l9()?$8()?i9()?(Y8("Requesting cast selector."),$8().requestSession()):(Y8("Wait for cast API to be ready to request the session."),m9.push(g.xi("yt-remote-cast2-api-ready",j$))):k9("requestCastSelector: Cast is not initialized."):k9("requestCastSelector: Cast API is not installed!")},k$=function(a){g.Vy.call(this,a);
this.A={key:g.ai(),name:g.P("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.jl(64);this.H=0},g$=function(a,b,c){a.F=c;
a.g.Qa("presentingplayerstatechange",new g.dC(c,b))},l$=function(a,b,c){if(b.key!=a.B.key)if(b.key==a.A.key)D9();
else{a.B=b;var d;if(!c){c=a.g.je();d=a.g.getVideoData().videoId;var e;if(c){e=[];for(var f=0;f<c.B;f++)e[f]=c.Qb(f).videoId}else e=[a.g.getVideoData().videoId];d={videoIds:e,listId:a.g.Ye(),videoId:d,index:Math.max(a.g.Rw(),0),currentTime:a.g.getCurrentTime()}}a=d;B9("Connecting to: "+g.lf(b));"cast-selector-receiver"==b.key?(c9(a||null),b=a||null,i9()?$8().setLaunchParams(b):k9("setLaunchParams called before ready.")):!a&&C9()&&e9()==b.key?o9("yt-remote-connection-change",!0):(D9(),c9(a||null),a=
g9().ud(),(b=g.ci(a,b.key))&&z9(b,1))}};
g.C(X8,g.Hz);g.h=X8.prototype;g.h.ud=function(a){return this.Ic.$_gs(a)};
g.h.contains=function(a){return!!this.Ic.$_c(a)};
g.h.get=function(a){return this.Ic.$_g(a)};
g.h.start=function(){this.Ic.$_st()};
g.h.Gl=function(a,b,c){this.Ic.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Ic.$_r(a,b,c)};
g.h.ul=function(a,b,c,d){this.Ic.$_un(a,b,c,d)};
g.h.R=function(){for(var a=0,b=this.o.length;a<b;++a)this.Ic.$_ubk(this.o[a]);this.o.length=0;this.Ic=null;X8.M.R.call(this)};
g.h.EJ=function(){this.aa("screenChange")};
g.h.pG=function(){this.aa("onlineScreenChange")};
var f9=null,m9=[],r9=null,y9=null;g.C(H9,g.Bn);g.h=H9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.v,(0,g.z)(function(){this.Lb("Failed to play video with cast v2 channel.");J9(this,"play")},this)):J9(this,"play"),O9(this,1,g.QB(I9(this))),this.aa("remotePlayerChange")):N9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.v,(0,g.z)(function(){this.Lb("Failed to pause video with cast v2 channel.");J9(this,"pause")},this)):J9(this,"pause"),O9(this,2,g.QB(I9(this))),this.aa("remotePlayerChange")):N9(this,this.pause)};
g.h.Gw=function(a){if(1==this.g){if(this.o){var b=I9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.gb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.v,(0,g.z)(function(){this.Lb("Failed to seek in video with cast v2 channel.");J9(this,"seekTo",{newTime:a})},this))}else J9(this,"seekTo",{newTime:a});
O9(this,3,a);this.aa("remotePlayerChange")}else N9(this,g.B(this.Gw,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.v,(0,g.z)(function(){this.Lb("Failed to stop video with cast v2 channel.");J9(this,"stopVideo")},this)):J9(this,"stopVideo");
var a=I9(this);g.OB(a);K9(this,a);this.aa("remotePlayerChange")}else N9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=I9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.z)(function(){P9("set receiver volume: "+d)},this),(0,g.z)(function(){this.Lb("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.z)(function(){P9("set receiver muted: "+b)},this),(0,g.z)(function(){this.Lb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);J9(this,"setVolume",e)}c.muted=b;c.volume=a;K9(this,c)}else N9(this,g.B(this.setVolume,a,b))};
g.h.Vv=function(a,b){if(1==this.g){var c=I9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.lf(b.style),g.Yb(d,c.o));J9(this,"setSubtitlesTrack",d);K9(this,c)}else N9(this,g.B(this.Vv,a,b))};
g.h.Ap=function(a,b){if(1==this.g){J9(this,"setAudioTrack",{videoId:a,audioTrackId:b.zc.id});var c=I9(this);c.audioTrackId=b.zc.id;K9(this,c)}else N9(this,g.B(this.Ap,a,b))};
g.h.Fw=function(a,b){if(1==this.g){if(a&&b){var c=I9(this);g.RB(c,a,b);K9(this,c)}J9(this,"previous")}else N9(this,g.B(this.Fw,a,b))};
g.h.Ew=function(a,b){if(1==this.g){if(a&&b){var c=I9(this);g.RB(c,a,b);K9(this,c)}J9(this,"next")}else N9(this,g.B(this.Ew,a,b))};
g.h.qs=function(){1==this.g?J9(this,"dismissAutoplay"):N9(this,this.qs)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.aa("proxyStateChange",a,this.g)}H9.M.dispose.call(this)};
g.h.R=function(){M9(this);this.B=null;this.C.clear();G9(this,null);H9.M.R.call(this)};
g.h.Bp=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.aa("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.KB(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.JG=function(a,b){this.aa(a,b)};
g.h.JE=function(a){if(!a)this.Hi(null),G9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=I9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)P9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,K9(this,b)}};
g.h.Hi=function(a){P9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Q9(this),this.aa("remotePlayerChange")};
g.h.IE=function(a){a?(Q9(this),this.aa("remotePlayerChange")):this.Hi(null)};
g.h.SE=function(){var a=w9();a&&G9(this,a)};
g.h.Lb=function(a){g.Dz("CP",a)};
var i$=[];g.h=U9.prototype;g.h.mg=function(a,b,c){var d=this.g;if(g.p(c)?c:this.o)d="https://"+this.A+this.B+this.g;return g.Tf(d+a,b||{})};
g.h.zp=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Bb:g.B(this.zJ,c,!0),onError:g.B(this.yJ,d),Tc:g.B(this.AJ,d)};b&&(c.Sb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ei(a,c)};
g.h.zJ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.yJ=function(a,b){a(Error("Request error: "+b.status))};
g.h.AJ=function(a){a(Error("request timed out"))};
g.C(V9,g.L);g.h=V9.prototype;
g.h.R=function(){V9.M.R.call(this);X9(this);f$(this);this.J();this.Z.removeEventListener("onVolumeChange",this.Pk,this);this.Z.removeEventListener("onCaptionsTrackListChanged",this.Ku,this);this.Z.removeEventListener("captionschanged",this.zu,this);this.Z.removeEventListener("videoplayerreset",this.Ki,this);this.Z.removeEventListener("captionssettingschanged",this.Zo,this);this.Z.removeEventListener("mdxautoplaycancel",this.Ir,this);this.g.Ja("proxyStateChange",this.Xu,this);this.g.Ja("remotePlayerChange",
this.Ji,this);this.g.Ja("remoteQueueChange",this.Ki,this);this.g.Ja("autoplayUpNext",this.xu,this);this.g.Ja("previousNextChange",this.Uu,this);this.g.Ja("nowAutoplaying",this.Nu,this);this.g.Ja("autoplayDismissed",this.wu,this);this.g=this.H=null};
g.h.ay=function(a,b){2==this.g.g||($9(this)?this.gC.apply(this,arguments):this.dC.apply(this,arguments))};
g.h.zu=function(a){this.ay("control_subtitles_set_track",g.Sb(a)?null:a)};
g.h.Zo=function(){var a=this.Z.Ec("captions","track");g.Sb(a)||b$(this,a)};
g.h.dC=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c$(this,this.Z.getCurrentTime());break;case "control_seek":c$(this,c[0]);break;case "control_subtitles_set_track":b$(this,c[0]);break;case "control_set_audio_track":c=c[0],$9(this)&&this.g.Ap(a$(this),c)}};
g.h.gC=function(a,b){if(1081!=I9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":I9(this.g).gb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Tg(c[0],c[1]);break;case "control_subtitles_set_track":b$(this,c[0]);break;case "control_set_audio_track":c=c[0],$9(this)&&this.g.Ap(a$(this),c)}}};
g.h.Pk=function(a){if($9(this)){this.g.Ja("remotePlayerChange",this.Ji,this);var b=Math.round(a.volume);a=!!a.muted;var c=I9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Ji,this)}};
g.h.Ku=function(){g.Sb(this.o)||d$(this,this.o);this.A=!1};
g.h.Xu=function(a,b){f$(this);2==b&&this.aw()};
g.h.Ji=function(){if($9(this)){X9(this);var a=I9(this.g);switch(a.g){case 1081:Y9(this,new g.jl(8));break;case 1:e$(this);Y9(this,new g.jl(8));break;case 1083:case 3:Y9(this,new g.jl(9));break;case 0:Y9(this,new g.jl(2));this.F.stop();W9(this,this.Z.getVideoData().lengthSeconds);break;case 1082:Y9(this,new g.jl(4));break;case 2:Y9(this,new g.jl(4));W9(this,g.QB(a));break;case -1:Y9(this,new g.jl(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.P("YTP_MDX_PLAYER_ERROR")},Y9(this,new g.jl(128,
a))}var a=I9(this.g).o,b=this.o;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.o=a,d$(this,a));a=I9(this.g);-1==a.volume||Math.round(this.Z.getVolume())==a.volume&&this.Z.Ad()==a.muted||this.G.isActive()||this.mw()}else Z9(this)};
g.h.Uu=function(){this.Z.Qa("mdxpreviousnextchange")};
g.h.Ki=function(){$9(this)||Z9(this)};
g.h.Ir=function(){this.g.qs()};
g.h.xu=function(a){a&&(a=g.Ei("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},Bb:(0,g.z)(this.DH,this)}))&&(this.J=(0,g.z)(a.abort,a))};
g.h.DH=function(a,b){var c=new g.my({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.Z.Qa("mdxautoplayupnext",c)};
g.h.Nu=function(a){(0,window.isNaN)(a)||this.Z.Qa("mdxnowautoplaying",a)};
g.h.wu=function(){this.Z.Qa("mdxautoplaycanceled")};
g.h.fM=function(a,b){-1==I9(this.g).g?c$(this,a):b&&this.g.Gw(a)};
g.h.mw=function(){if($9(this)){var a=I9(this.g);this.Z.removeEventListener("onVolumeChange",this.Pk,this);a.muted?this.Z.mute():this.Z.Vf();this.Z.setVolume(a.volume);this.Z.addEventListener("onVolumeChange",this.Pk,this)}};
g.h.aw=function(){f$(this);X9(this);var a=this.g.B.getReconnectTimeout();2!=this.g.g||(0,window.isNaN)(a)||(this.C=g.Qg((0,g.z)(this.aw,this),1E3))};
g.C(k$,g.Vy);g.h=k$.prototype;g.h.create=function(){tra("embedded"==g.V(this.g).g);this.D.push(g.xi("yt-remote-before-disconnect",this.FE,this));this.D.push(g.xi("yt-remote-connection-change",this.RG,this));this.D.push(g.xi("yt-remote-receiver-availability-change",this.Vu,this));this.D.push(g.xi("yt-remote-auto-connect",this.PG,this));this.D.push(g.xi("yt-remote-receiver-resumed",this.OG,this));this.Vu()};
g.h.load=function(){this.g.Rm();k$.M.load.call(this);this.C=new V9(this,this.g,this.o);var a;a=(a=t9())?a.currentTime:0;var b=C9()?new H9(b9(),void 0):null;0==a&&b&&(a=g.QB(I9(b)));0!=a&&(this.H=a||0,this.g.Qa("progresssync",a,void 0));g$(this,this.F,this.F);g.V4(this.g.app,6)};
g.h.unload=function(){this.g.Qa("mdxautoplaycanceled");this.B=this.A;g.Cb(this.C,this.o);this.o=this.C=null;k$.M.unload.call(this);g.V4(this.g.app,5)};
g.h.R=function(){g.yi(this.D);k$.M.R.call(this)};
g.h.nj=function(a,b){this.loaded&&this.C.ay.apply(this.C,arguments)};
g.h.JB=function(){return this.loaded?this.C.suggestion:null};
g.h.Bx=function(){return this.o?I9(this.o).L:!1};
g.h.hasNext=function(){return this.o?I9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.HL=function(){var a=I9(this.o),b=this.g.getVideoData(),c=g.bm(this.g),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.G)()-a.A)/1E3:a.B;var l=1>=W8(a)-this.getCurrentTime(),m=a.J,n=W8(a),a=0<a.C?a.C+((0,g.G)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.IL=function(){this.o&&this.o.Ew()};
g.h.JL=function(){this.o&&this.o.Fw()};
g.h.FE=function(a){1==a&&(this.J=this.o?I9(this.o):null)};
g.h.RG=function(){var a=C9()?new H9(b9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Bb(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.Fc(g.QB(a)));this.g.Qa("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.Vu=function(){this.G=[this.A].concat(sra());var a=h$()||this.A;l$(this,a,!this.loaded);this.g.ya("onMdxReceiversChange")};
g.h.PG=function(){var a=h$();l$(this,a)};
g.h.OG=function(){this.B=h$()};
g.h.GL=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?j$():l$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&j$(),!0):!1}};
g.h.KL=function(){J9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Ve=function(){return!1};
window._exportCheck==g.wa&&g.ka("ytmod.player.remote",k$,void 0);})(_yt_player);
