/* src: 2017-01-24 18:28:39 */
/* gen: 2017-01-24 18:29:28 */
(function(){function Mb(f,k,q,u){var ma=!1,n=!1;f=nb({event_type:"getBlockNum",event:f},k,void 0);Nb(f,function(f,k){ma=!0;if(n)return!1;q(f,k)});setTimeout(function(){n=!0;if(ma)return!1;u()},250)}function Ha(f,k,q,u,ma){f={M:u||!1,v:ma||!1,src:f,ca:k,da:q};f[Ta]=Ua();return f}function nb(f,k,q){var u=k.ca,ma=k.da,n=k.src;f.type="event";f.rnd=Ua();f.sender_id=Ta;f.prefix=sa[0];f.broadcast=q||!1;k.M&&(f["for"]=k.M);k=!1;q=null;if(!~Ob.indexOf("iphone"))try{q="*"==u?!0:n.location.protocol+"//"+n.location.hostname==
u}catch(C){}if(null===q||q)n.postMessage(ma+"|"+JSON.stringify(f),u),k=f.rnd;return k}function Pb(f,k,q){var u=null;q=q||!1;k=k||{};u=u||function(f){return f};C(M,function(n){if(~M[n].o.indexOf(f)||~M[n].o.indexOf("*")){var B=u(S(k),J(M[n].K[f],{}));!1!==B&&(B={event_type:f,event:B},q&&(B.source_rnd=q),nb(B,M[n].ea,!1))}})}function Qb(f,k,q){var u=Ha(f.source,f.origin,J(k.prefix,q),J(k.rnd),J(k["for"]));u.v&&U(ha[u.v])?ha[u.v]&&(ha[u.v](k.event,u),ha[u.v]=null):C(za,function(f){if(za[f]&&~za[f].o.indexOf(k.event_type)&&
0===za[f].ha(k.event,u))return!1})}function Nb(f,k){ha[f]=k}function Rb(){}function Ua(){var f;f=99*Math.random();if(U(void 0)){var k;k=Math.pow(10,void 0);f=Math.round(f*k)/k}else f=Math.round(f);return(new Date).getTime()%1E7*100+f}function U(f){return"undefined"!=typeof f}function J(f,k){k=U(k)?k:!1;return U(f)?f:k}function Sb(f,k){C(k,function(q){f[q]=k[q]})}function C(f,k){for(var q in f)if(f.hasOwnProperty(q)&&"length"!==q&&!1===k.call(f[q],q,f[q]))break}function Va(f){for(var k={},q=[],u=f.length,
n=0,B=0;B<u;B++){var C=f[B];1!==k[C]&&(k[C]=1,q[n++]=C)}return q}function S(f,k){if(null==f||"object"!==typeof f)return f;if(void 0==k)k=[];else{var q,u=k.length;for(q=0;q<u;q++)if(f===k[q])return f}k.push(f);if("function"==typeof f.clone)return f.clone(!0);if("[object Array]"==Object.prototype.toString.call(f)){u=f.slice();for(q=u.length;q--;)u[q]=S(u[q],k);return u}if(f instanceof Date)return new Date(f.getTime());if(f instanceof RegExp)return new RegExp(f);if(f.nodeType&&"function"==typeof f.cloneNode)return f.cloneNode(!0);
q=Object.getPrototypeOf?Object.getPrototypeOf(f):f.__proto__;q||(q=f.constructor.prototype);var u=Wa(q),n;for(n in f)u[n]=S(f[n],k);return u}function Xa(f,k){function q(){y({"div[id^=adriver_banner_]":"adriver","div[id^=AdFox_banner_]":"adfox","iframe[id^=AdFox_plug_]":"adfox","ins.adsbygoogle[data-ad-client^=ca-pub-3104790387792468]":"npm","ins[id^=aswift_]>ins[id^=aswift_]>iframe":"adsense","div[id^=div-gpt]>div[id^=google_ads_iframe_]>iframe[id^=google_ads_iframe_]":"dfp","div[id^=eplAdDivBanner]>iframe[id^=ifr]":"e-planning"},
function(a,b){var c=r.querySelectorAll(a);c.length&&y(c,function(a){if(1==c[a].getAttribute("data-___lx_atf"))return!0;if(ia()>Aa(c[a]).top){var d=ob(c[a]);ja(c[a]);d&&100<d.height&&(Ya(c[a],"data-___lx_atf",1),u(c[a],{sid:pb,type:b,h:d.height,w:d.width}))}else return!1})})}function u(a,b){b=b||{};setTimeout(function(a,b){return function(){T(P+"luxupcdna.com/npm_mobile_atf_problems/?rt="+Z()+"&loc="+encodeURIComponent(r.location.href)+yc(b),function(){})}}(a,b),0)}function n(a,b){var c=!1;if(!a||
!~b.indexOf("js/adsbygoogle.js"))return c;var e=ob(a),d=ob(a.parentNode),t=320;e&&e.width&&320>e.width?t=300:d&&d.width&&320>d.width&&(t=300);e='style="display:inline-block;width:'+t+'px;height:100px;"';d=/style="display: *?inline-block; *?width: *?\d+?px; *?height: *?\d+?px;"/m;/data-ad-format="(\w|,)+?"/m.test(b)&&(c=b.replace('style="display:block"',""),c=c.replace('style="display:inline-block;"',e),c=c.replace(/data-ad-format="(\w|,)+?"/mg,""));!(new RegExp('style="display:inline-block;width:'+
t+'px;height:100px;"',"m")).test(b)&&d.test(b)&&(c=b.replace(d,e));c&&(e=/data-alternate-ad-url="(.+?)"/mg,d=e.exec(c),null!=d&&(c=c.replace(e,'data-alternate-ad-url="$1'+(~d[1].indexOf("?")?"&":"?")+"w="+t+'&h=100&js_resize=1"')));return c}function B(a){for(var b=a.c.I.length,c=J(a.ai_min_space),e=J(a.ai_1_space),d=null,t=null,D=!1,g=b?Tb(a.c.I[b-1].a):0;!D;){d=a.c.m.shift();if(!d)break;t=Tb(d);(D=(b?g+c:e)<t)&&a.c.F&&a.c.F.length&&y(a.c.F,function(a,b){y(b.Ja,function(a,c){var d=Aa(c).top,e=d+v(c.offsetHeight);
if(d>t&&d-b.oa<t||e<t&&e+b.oa>t||d==t||e==t)return D=!1});if(!D)return!1})}return D?d:null}function C(a,b,c){c=c||!1;if(!(a.c.H&&!b||a.c.I.length>=a.ai_max_count)&&(a.c.H=!0,null==a.c.m&&(a.c.m=r.querySelectorAll(a.location),a.c.m&&a.c.m.length&&(a.c.m=Array.prototype.slice.call(a.c.m,0)),a.P&&y(a.c.m,function(b,c){ia()>Aa(c).top&&a.c.m.splice(b,1)})),a.c.m.length)){if(l(a.ai_border_check)&&null==a.c.F){a.c.F=[];b=a.ai_border_check;b=b.split(",");var e=J(a.ai_min_space);y(b,function(b,c){var d=e;
~c.indexOf(":")&&(c=c.split(":"),d=J(c[1]),c=c[0]);var t=r.querySelectorAll(c);t&&t.length&&a.c.F.push({Ya:c,oa:d,Ja:t})})}var d=B(a);b=null;if(d){b={};var t=c?c:1+a.c.I.length,D=a.c.id+"."+t;b.a=H("div");b.a.id=a.id;b.a.setAttribute("data-cnt",t);b.a.className="__lxG__multi __lxG__multi_"+a.id;a.c.ma?a.c.ma(d,b.a,{}):d.parentNode.insertBefore(b.a,d.nextSibling);d={};a.c.source?("iframe"==a.c.Oa?(a.c.qa&&Q(b.a,a.c.qa),aa(b.a,a.c.source,a.c.width,a.c.height,r,!1,l(a.c.Pa,!0))):Q(b.a,a.c.source),N(a.c)):
(d=function(a,b,c){return function(){c.Za=null;T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(a){return function(){a.c.H=!1;a.c.m.length&&Ga(a)&&C(a,!0)}}(b))}}(D,a,d),c?d():zc("getBlockNum",{ids:[D]},Ia,function(a,b,c){return function(d){d=d.ids;d.length&&(a=d[0]["new"],b.a.setAttribute("data-cnt",d[0].cnt));T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(a){return function(){a.c.H=!1;a.c.m.length&&Ga(a)&&C(a,!0)}}(c));return-1}}(D,b,a),d));a.c.I.push(b);l(a.refresh)&&(a.l=setTimeout(Ac(a,
t),1E3*a.refresh))}l(a.ai_clone_source)&&b&&a.c.m.length&&Ga(a)&&C(a,!0);a.c.H=!1}}function Ga(a){var b=a.c.I;if(!b||!b.length||b.length>=a.ai_max_count)return!1;var b=Tb(b[b.length-1].a),c=J(a.ai_min_space),e=v(!Ja||h.opera||Za||"unknown"!=na()?O.scrollTop:ba.scrollTop);return b+c<e+ia()*(a.ai_preload+1)}function J(a){a=l(a,!1);if(!1!==a){var b=/((\d|\.|,)+?)s/im.exec(a);null!=b?a=Math.round(parseFloat(b[1])*ia()):a=v(a)}return a}function M(a,b,c){.1<(b-a.a.volume)*c?(a.a.volume=V(a.a.volume+.1*
c,2),oa[a.g]=setTimeout(function(){M(a,b,c)},25)):a.a.volume=b}function sd(a){oa[a.g]&&clearTimeout(oa[a.g]);oa[a.g]=setTimeout(function(){0<a.a.volume&&M(a,0,-1)},100)}function L(a){oa[a.g]&&clearTimeout(oa[a.g]);oa[a.g]=setTimeout(function(){1>a.a.volume&&M(a,.6,1)},100)}function Bc(a){Ub(a,-1,function(){return function(){$a(h,"focus scroll",a.va);delete oa[a.g];delete Ka[a.g];delete ab[a.g];a.j.ka?a.A.parentNode.removeChild(a.A):(a.href.parentNode.removeChild(a.href),a.Z.parentNode.removeChild(a.Z),
a.W.parentNode.removeChild(a.W),a.U.parentNode.removeChild(a.U),a.T.parentNode.removeChild(a.T))}}())}function td(a,b){var c=b.type;if("pause"!=c||a.a.duration!=a.a.currentTime){"play"==c&&0==a.a.currentTime&&(c="started");if("timeupdate"==c){if(a.j.J)for(var e in a.j.J)if(a.j.J.hasOwnProperty(e)){var d=v(e.replace("_",""));if(a.a.duration*d/100<=a.a.currentTime){for(d=a.j.J[e].length;d--;)H("img").src=a.j.J[e][d];delete a.j.J[e]}}100!=a.j.ja&&!a.Y&&a.a.duration*a.j.ja/100<=a.a.currentTime&&(a.Y=
!0,setTimeout(function(){T(a.j.ua,function(){})},0))}"started"==c&&setTimeout(function(){T(a.j.Ra,function(){})},0);"ended"==c&&(a.Y||setTimeout(function(){T(a.j.ua,function(){})},0),Bc(a))}}function S(a){if(!a.B){for(var b=!1,c=ia(),e=a.a.getClientRects(),d=0,t=e.length;d<t;d++){var D=e[d];if(0<=D.top&&D.top<c){b=!0;break}}b&&Ub(a,1,function(){return function(){U(a)}}())}a.B&&a.a.duration!=a.a.currentTime&&((b=Cc(a.a))&&a.a.paused?a.a.play():b||a.a.pause())}function U(a){Ka[a.g]&&clearTimeout(Ka[a.g]);
Ka[a.g]=setTimeout(function(){S(a)},50)}function Ub(a,b,c){ab[a.g]&&clearTimeout(ab[a.g]);var e=ja(a.A),d=v(e.height),t=a.j.ka?0:120;1==b&&d<a.a.height||-1==b&&d>t?(a.A.style.height=d+5*b+z,1==b?a.A.style.opacity=parseFloat(e.opacity)+V(1/(a.a.height/5),3)*b:(e=ja(a.href),a.href.style.opacity=parseFloat(e.opacity)+V(1/((a.a.height-t)/5),3)*b,a.Z.style.opacity=a.href.style.opacity,a.W.style.opacity=a.href.style.opacity,a.U.style.opacity=a.href.style.opacity,a.T.style.opacity=a.href.style.opacity),
ab[a.g]=setTimeout(function(){Ub(a,b,c)},10)):(1==b?(a.B=1==b,a.A.style.opacity=v(a.B)):-1==b&&0==t&&(a.A.style.display="none"),c())}function sa(a,b){if(!Dc){Dc=!0;var c=H("link");c.setAttribute("rel","stylesheet");c.setAttribute(Vb,"text/css");c.href=P+"s.luxupcdna.com/images/i/video26/videostyle.css";bb.appendChild(c)}var e={g:Z(),B:!1};oa[e.g]=Ka[e.g]=ab[e.g]=!1;e.j=b;e.Y=!1;c=H("div");c.style.cssText=b.ya;c.style.width=b.V+z;c.style.height=0+z;c.style.margin="0 auto";c.style.textAlign="center";
c.style.display="block";c.style.overflow="hidden";c.style.opacity=0;c.style.position="relative";A(c,"lx_amn_inlvid");var d=H("a");d.href="javascript:void(0);";A(d,"ico");d.appendChild(H("span"));var t=H("a");t.href=b.ia;t.target="_blank";A(t,"vid");var D=H("video");D.width=b.V;D.height=Ec(b.V/(b.Ta/b.Qa));D.controls=!1;D.autoplay=!1;D.volume=0;var g=H("source");g.src=b.Sa;D.appendChild(g);e.a=D;e.A=c;e.href=t;e.Z=d;e.nextSibling=a.nextSibling;e.previousSibling=a;g=H("a");g.href="javascript:void(0);";
g.innerHTML="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";E(g,"click",function(){return function(a){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;Bc(e);return!1}}());A(g,"cls");e.W=g;b.Ba&&(g.style.display="none");var f=H("a");f.href="javascript:void(0);";f.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">\u0420\u0435\u043a\u043b\u0430\u043c\u0430</span>';A(f,"adv");e.U=f;b.Ca&&(f.style.display="none");var m=H("a");m.href="javascript:void(0);";m.innerHTML='<span class="bg_lnk"></span><span class="txt_lnk">'+
e.j.pa+"</span>";A(m,"adv_txt");e.T=m;e.j.pa||(m.style.display="none");var l=H("div");A(l,"dsc");l.innerHTML='<span><a href="http://video.adlabsnetworks.com/?utm_source=partners&utm_medium=logo" target="_blank">Powered by</a></span>';var k=H("a");k.href=b.ia;k.target="_blank";l.appendChild(k);k.innerHTML="\u041f\u0435\u0440\u0435\u0439\u0442\u0438 \u043d\u0430 \u0441\u0430\u0439\u0442 \u0440\u0435\u043a\u043b\u0430\u043c\u043e\u0434\u0430\u0442\u0435\u043b\u044f";E(D,"play pause ended timeupdate",
function(){return function(a){td(e,a)}}());E(D,"mouseover",function(){return function(){L(e)}}());E(D,"mouseout",function(){return function(){sd(e)}}());E(t,"click",function(){return function(){e.a.pause();return!0}}());e.va=function(){return function(){U(e)}}();E(h,"focus scroll",e.va);t.appendChild(D);c.appendChild(g);c.appendChild(f);c.appendChild(m);c.appendChild(d);c.appendChild(t);c.appendChild(l);a.parentNode.insertBefore(c,a.nextSibling);Ka[e.g]=setTimeout(function(){U(e)},50)}function da(a){var b=
new Date,c=b.getTime();b.setTime(c+2592E6);ca.set(Wb,a,b,"/");ca.set(Fc,ca.get(Gc,0),b,"/");ca.set(Gc,c,b,"/")}function Ac(a,b){return function(){if(a.u)return!1;a.l&&clearTimeout(a.l);a.u=!0;var c=null;y(F,function(b){if(F[b]===a)return c=b.replace("_",""),!1});var e=qb("lx_"+c,b);if(e&&"none"==e.style.display)return!1;!1!==l(a.refresh_limit)&&a.refresh_limit--;T(P+"luxupcdna.com/multishows/"+c+(b?"."+b:"")+"/"+ta(),function(){a.u=!1})}}function pa(a,b){p(h.__lxG__.multishows_params)&&l(h.__lxG__.multishows_params.preventautorefresh)||
!l(a.refresh)||!l(a.refresh_limit,!0)||(a.l=setTimeout(Ac(a,b||null),1E3*a.refresh))}function ha(a,b,c){b.buffer={x:[],y:[]};b.buffer.Aa=function(a,b,c){return function(a){if(a||h.event)a=a||h.event,a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;c.style.display="none";return b.G=!0}}(a,b,c);E(c.querySelectorAll(".lx_close"),"click",b.buffer.Aa);b.buffer.show=function(a,b,c){return function(D){var g=D.pageY;b.buffer.x.push(D.pageX);b.buffer.y.push(g);b.buffer.x=b.buffer.x.slice(-5);b.buffer.y=
b.buffer.y.slice(-5);var h=!1;y(b.buffer.y,function(a,c){if(v(a))if(c<=b.buffer.y[a-1])h=!0;else return h=!1});h&&30>g&&($a(r,"mousemove",b.buffer.show),c.style.display="block",N(a))}}(a,b,c);E(r,"mousemove",b.buffer.show)}function Hc(a){for(var b=!1,c=cb("meta",!0),e=c.length;e--;)if(p(c[e].name)&&"viewport"==c[e].name){var d=c[e].content;if(~d.indexOf(a)&&(d=(new RegExp(a+" *?= *?(.+?)(?:[, ]|$)","m")).exec(d),null!=d)){b=d[1];break}}return b}function qa(){if(-1===rb){rb=!1;for(var a=cb("meta",
!0),b=a.length;b--;)if(p(a[b].content)){var c=a[b].content;if(~c.indexOf("width=device-width")||~c.indexOf("initial-scale=1")||~c.indexOf("user-scalable=no")){rb=!0;break}}}return rb}function za(a){var b=ea();b&&(Xb=b.getAttribute("content"));a=a||"width=device-width";b?Ya(b,"content",a):(r.getElementsByTagName("head").length||r.insertBefore(H("head"),r.getElementsByTagName("body")[0]),b=H("meta"),b.name="viewport",b.content=a,cb("head").appendChild(b))}function ea(){for(var a=!1,b=cb("meta",!0),
c=b.length;c--;)if(p(b[c].name)&&"viewport"==b[c].name){a=b[c];break}return a}function Ra(a){return function(){if(a.u)return!1;a.l&&clearTimeout(a.l);a.u=!0;Ic(a.N)}}function Ha(a,b){setTimeout(function(){var c=parseInt(a.style.right);0<b&&0==c||0>b&&c==Yb(a)||(c+=6*b,0<c&&(c=0),c<Yb(a)&&(c=Yb(a)),a.style.right=c+"px",Ha(a,b))},10)}function Ta(a){return function(){ua()?A(a.a,"lxm_landscape"):db(a.a,"lxm_landscape");r.getElementById("lx_dbg_fullscreen")&&(r.getElementById("lx_dbg_fullscreen").innerHTML=
a.a.className);return!1}}function Ua(a){return function(b){b.stopPropagation();var c=K("lx_links_position",a.a)[0];Zb(c,"anishow")?(A(c,"anihide"),db(c,"anishow")):(A(c,"anishow"),db(c,"anihide"));b.preventDefault();return!1}}function Wa(){return function(a){a.stopPropagation();var b=p(this.style)?v(l(this.style.right,0)):0;return v(a.pageX)-v(this.offsetLeft)<this.getAttribute("triggerWidth")?(b!=this.getAttribute("baseStyleRight")&&0!=b||Ha(this,0==b?-1:1),a.preventDefault(),!1):!0}}function Xa(a,
b){return function(c){if(c||h.event)c=c||h.event,c.stopPropagation?c.stopPropagation():c.cancelBubble=!0,c.preventDefault&&c.preventDefault();c=K("lxm_sl",a.a)[0];c.style.display="";c=K("lxm_button",c)[0];c.href=b.href;c.title=b.title;return!1}}function kb(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;K("lxm_sl",a.a)[0].style.display="";return!1}}function mb(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():
b.cancelBubble=!0;a.a.style.display="none";a.G=!0;a.$&&(b=ea(),Xb?Ya(b,"content",Xb):b.parentNode.removeChild(b));if(eb(a.closeTimeout)&&(b=eb(a.closeTimeout))){var c=new Date;c.setTime(c.getTime()+6E4*b);ca.set("_lxblockignore_"+a.N,1,c,"/")}return!0}}function Sa(a,b,c){!1!==c&&A(a,"lxm_"+b+"_"+(.5*Math.ceil(parseFloat(c)/.5)).toString().replace(".","_"))}function nb(){var a=na(),b=Va(),c=1,c=qa()?1/b:(1.144>b?1:2.75<b?1.26:4.431914*Math.pow(b,8)-65.6671503*Math.pow(b,7)+417.3583138*Math.pow(b,6)-
1484.928018*Math.pow(b,5)+3233.105604*Math.pow(b,4)-4410.2163548*Math.pow(b,3)+3680.9724495*Math.pow(b,2)-1719.2504263*b+345.6426082)/b;a==R&&3>Ba&&!ua()?c=1.3*b:ua()&&(c*=1.15);return c=V(100*c)}function Va(){if(Jc!=$b){var a=na(),b=1,c=qa()?1:window.devicePixelRatio;a==fb&&~ka.indexOf("iphone")&&!qa()&&(c=2);b=ba.clientWidth/h.innerWidth/c;if(~ka.indexOf("ipad")||a==R&&Ca&&1<c)b*=c;ua()&&a==R&&!qa()?b*=2:ua()&&a==R&&qa()&&(b*=.85);!ua()&&Ca&&a==R?b/=(Ba(),1.5):ua()&&Ca&&a==R&&!qa()&&(b/=4<=Ba()?
1.75:1.5);Kc=V(100*b)/100;Jc=$b}return Kc}function ua(){var a=na(),b=0===window.orientation||180===window.orientation;return Ca&&a==R&&4<=Ba()?!b:Ca&&a==R?b:!b}function na(){if(!sb){sb="unknown";for(var a=[[R,R],["ipad",fb],["iphone",fb],["ipod",fb]],b=0;b<a.length;b++)if(~ka.indexOf(a[b][0])){sb=a[b][1];break}}return sb}function Ba(){if(!1===tb){var a=na();tb=0;a==R&&(tb=parseFloat(ka.slice(ka.indexOf(R)+8)))}return tb}function lb(a){if(!ac){var b=0;ac=!0;$b++;for(var c in W)if(W.hasOwnProperty(c)){var e=
W[c];if(!e.na&&!e.$&&!e.G){var d=e.a,t=Va(),D=nb(),g=[h.pageXOffset,h.pageYOffset],f=[h.pageXOffset,h.pageYOffset+h.innerHeight];d.style.width=g[0]+h.innerWidth-g[0]+z;na()==R&&4<=Ba()||(d.style.left=g[0]+z,d.style.top=e.Ea?f[1]-d.offsetHeight+z:g[1]+z);ua()?A(d,"lxm_landscape"):db(d,"lxm_landscape");t=Math.ceil(e.Da/t);d.style.height=t+z;ub(e.Ga,"height",t+z);ub(e.Ia,"lineHeight",t+z);e.fa&&(d=Ec(t*(qa()?.8:.95))+z,e.fa.style.height=d,e.fa.style.width=d);d=qa()?100:50>D?80:100;ub(e.Fa,"fontSize",
D+"%");ub(e.Ha,"lineHeight",d+"%");b++}}b&&a&&(bc&&clearTimeout(bc),bc=setTimeout(function(){lb(!1)},250));ac=!1}}function Lc(){cc&&clearTimeout(cc);cc=setTimeout(function(){lb(!0)},250)}function Mb(a,b){var c=dc(a.a);if(b){for(var e in c)c.hasOwnProperty(e)&&v(c[e])&&"lxm_"==e.substring(0,4)&&A(a.a,e);A(a.a,"lxm_os_"+na());qa()&&A(a.a,"lxm_meta_set");p(h.devicePixelRatio)&&A(a.a,"lxm_pixel_ratio_"+Math.ceil(h.devicePixelRatio))}for(var d=K("lxm_js_block_close",a.a),t=d.length;t--;)E(d[t],fa,mb(a));
a.na=!1;a.$=!1;if(eb(c.lxm_fullscreen)){a.$=!0;za();d=K("lxm_sl_trigger",a.a);for(t=d.length;t--;)E(d[t],fa,Xa(a,d[t]));var D=K("lxm_sl",a.a)[0],c=K("lxm_button_close",D)[0];E(c,fa,function(){return function(){D.style.display="none"}}());p(screen.width)&&A(a.a,"lxm_scr_"+250*Math.ceil(Math.max(screen.width,screen.height)/250));c=h.innerHeight||0;A(a.a,"lxm_scr_width_"+100*Math.ceil((h.innerWidth||0)/100));A(a.a,"lxm_scr_height_"+100*Math.ceil(c/100));Sa(a.a,"minscale",Hc("minimum-scale"));Sa(a.a,
"initscale",Hc("initial-scale"));c="lxm_zoom_"+(.25*Math.ceil(ba.clientWidth/h.innerWidth/.25)).toString().replace(".","_");A(a.a,c);c=K("lx_hide_logo",a.a);for(d=c.length;d--;)E(c[d],fa,Ua(a));c=Ta(a);d=["orientationchange","touchmove","touchend",La,"resize"];for(e in d)d.hasOwnProperty(e)&&E(h,d[e],c);c()}else{d=K("lxm_sl_trigger",a.a);for(t=d.length;t--;)E(d[t],fa,kb(a));if(eb(c.lxm_static))for(a.na=!0,c=K("lxm_banner_sc",a.a),d=c.length;d--;)E(c[d],fa,Wa());else{b&&(na()==R&&4<=Ba()||(a.a.style.position=
vb,a.a.style[Mc]="auto"),a.Da=eb(c.initheight),a.Ea=Zb(a.a,"lxm_bottom"),a.fa=Zb(a.a,"lxm_tizer")?K("lxm_tizer_img",a.a)[0]:!1,a.Fa=K("lxm_js_fontsize",a.a),a.Ha=K("lxm_js_lineheight",a.a),a.Ia=K("lxm_js_lineheightpx",a.a),a.Ga=K("lxm_js_height",a.a));if(!Nc){if(na()==R&&3>Ba())e=H("meta"),e.name="viewport",e.content="width=device-width",r.head.appendChild(e);else for(e in d=["orientationchange","touchmove","touchend",La,"resize"],d)d.hasOwnProperty(e)&&E(h,d[e],Lc);Nc=!0}p(a.refresh)&&a.refresh&&
(a.l&&clearTimeout(a.l),a.l=setTimeout(Ra(a),1E3*a.refresh));Lc()}}}function ec(a,b){a.B=!1;p(a.D)&&clearInterval(a.D);clearTimeout(a.l);a.L&&clearTimeout(a.L);a.D=setInterval(function(){var c=Oc(a),e=c-22;c>=-a.width&&e>-a.width?(a.O=!0,a.a.style[a.side]=e+z):(clearInterval(a.D),a.O=!1,a.a.style[a.side]=-a.width+z,a.a.style.display="none",p(b)&&b());wb&&xb(a)()},15)}function Nb(a){return function(){a.L&&clearTimeout(a.L);a.aa=!1;a.ba&&T(fc+encodeURIComponent(a.ba),function(){})}}function Ob(a){a.B=
!0;p(a.D)&&clearInterval(a.D);clearTimeout(a.l);a.l=setTimeout(Pc(a),1E3*a.refresh);a.a.style.display="block";a.D=setInterval(function(){var b=Oc(a),c=b+22;0>b&&0>c?(a.O=!0,a.a.style[a.side]=c+z):(clearInterval(a.D),a.O=!1,a.a.style[a.side]=0+z,a.aa&&(a.L=setTimeout(Nb(a),1E3)));wb&&xb(a)()},15)}function Oc(a){var b=0;return b=wb?a.a[a.side+"Offset"]:v(a.a.style[a.side])}function Qc(a){return function(){p(a.la)&&clearTimeout(a.la);a.la=setTimeout(xb(a),100)}}function xb(a){return function(){a.a[a.side+
"Offset"]=v(a.a.style[a.side]);var b={bottom:!0};"left"==a.side&&(b.left=!0);"right"==a.side&&(b.right=!0);pinBlock(a.a,b)}}function Rc(a){return function(){if(!a.G&&!a.u){var b=v(ba.scrollTop?ba.scrollTop:O.scrollTop);!a.B&&b>=a.limit?Ob(a):a.B&&b<a.limit&&ec(a)}}}function Pc(a){return function(b){if(b||h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;clearTimeout(a.l);a.u=!0;ec(a,function(){T(P+"luxupcdna.com/multishows/"+a.N+"/"+ta(),function(){})})}}function Pb(a){return function(b){if(b||
h.event)b=b||h.event,b.stopPropagation?b.stopPropagation():b.cancelBubble=!0;a.G=!0;ec(a);b=new Date;b.setTime(b.getTime()+5925924E4);ca.set(gc(),1,b,"/")}}function Qb(a,b){b&&(E(r,La,Rc(a)),wb&&(xb(a)(),E(h,"resize",Qc(a)),E(h,La,Qc(a))));for(var c=K("close",a.a),e=c.length,d=0;d<e;d++)E(c[d],fa,Pb(a));c=K("ref",a.a);e=c.length;for(d=0;d<e;d++)E(c[d],fa,Pc(a))}function N(a,b){p(a.counters)&&(b=b||r,y(a.counters,function(a,e){H("img",b).src=e+"&_lxrnd_="+Z()}));3>=V(100*Math.random())&&Sc("https://pixel.adsafeprotected.com/jload?anId=924203&campId="+
pb+"&placementId="+l(a.id,0)+"")}function Rb(a){y(a,function(a,c){if(l(c.id)){var e=c.id+(l(c.sub_id)?"."+c.sub_id:"");null===Da&&(Da={});Da[e]=c}else~ud.indexOf(l(c.type))?hc.push(c):~vd.indexOf(l(c.type))&&hc.push(c)})}function Sb(a,b,c){a=Ma("getBlockNum",a,b);Tc(a,function(a,b){c(a,b)})}function zc(a,b,c,e,d){var t=!1,h=!1;a=Ma(a,b,c);Tc(a,function(a,b){t=!0;if(h)return!1;e(a,b)});setTimeout(function(){h=!0;if(t)return!1;d()},250)}function yb(a,b,c,e,d){a={M:e||!1,v:d||!1,src:a,ca:b,da:c};a[ic]=
Z();return a}function Ma(a,b,c){return zb("event",{event_type:a,event:b},c,void 0)}function zb(a,b,c,e){var d=c.ca,t=c.da,h=c.src;b.type=a;b.rnd=Z();b.sender_id=ic;b.prefix=Ab[0];b.broadcast=e||!1;c.M&&(b["for"]=c.M);a=!1;c=null;if(!~ka.indexOf("iphone"))try{c="*"==d?!0:h.location.protocol+"//"+h.location.hostname==d}catch(g){}if(null===c||c)h.postMessage(t+"|"+JSON.stringify(b),d),a=b.rnd;return a}function wd(a,b,c){var e=null;c=c||!1;b=b||{};e=e||function(a){return a};y(ga,function(d){if(~ga[d].o.indexOf(a)||
~ga[d].o.indexOf("*")){var t=e(jc(b),l(ga[d].K[a],{}));!1!==t&&(t={event_type:a,event:t},c&&(t.source_rnd=c),zb("event",t,ga[d].ea,!1))}})}function xd(a,b,c){var e=yb(a.source,a.origin,l(b.prefix,c),l(b.rnd),l(b["for"]));e.v&&p(gb[e.v])?gb[e.v]&&(gb[e.v](b.event,e),gb[e.v]=null):y(hb,function(a){if(hb[a]&&~hb[a].o.indexOf(b.event_type)&&0===hb[a].ha(b.event,e))return!1})}function Tc(a,b){gb[a]=b}function va(a,b){a=Array.isArray(a)?a:[a];hb.push({o:a,ha:b})}function yd(a,b){b=b||h.event;var c=b.target,
e=H("A");e.id="FakeLink";O.appendChild(e);var d=r.createEvent("MouseEvents");d.initMouseEvent("click",!!c,!0,h,1,!1,!1,!1,!1,!0,!1,!1,!1,!1,null);e.href=a;e.target="_blank";e.dispatchEvent(d)}function zd(a){var b=h.open("about:blank",x+"popunder","toolbar=0,scrollbars=1,location=1,statusbar=1,menubar=0,resizable=1,top=0,left=0,width="+h.screen.availWidth+",height="+h.screen.availHeight+"");if(b){b.blur();try{b.opener.focus()}catch(c){}b.location=a}}function Uc(a){var b=h.open("about:blank",x+"popunder",
"resizable=1,toolbar=0,location=1,menubar=1,directories=0,width="+h.screen.availWidth+",height="+h.screen.availHeight+",scrollbars=1");b&&(b.blur(),b.xa=function(c){with(c)Params=c.Va,Main=function(){p(window.mozPaintCount)&&window.open("about:blank").close();try{opener.window.focus()}catch(c){}b.location=a},Main()},b.xa(b),b.blur())}function Vc(){Na&&clearTimeout(Na);Na=setTimeout(Ad,500)}function Ad(){Na&&(clearTimeout(Na),Na=null);for(var a=Ea.length,b=0;b<a;b++)if(Ea[b]){var c=Ea[b][1];Cc(Ea[b][0])&&
(delete Ea[b],T(fc+encodeURIComponent(c),function(){}))}}function Cc(a){if(0===a.offsetWidth||0===a.offsetHeight)return!1;for(var b=ia(),c=Ja&&!h.opera?ba.clientWidth:O.clientWidth,e=a.getClientRects(),d=0,t=e.length;d<t;d++){var f=e[d],g=f.height?f.height:f.bottom-f.top,l=f.width?f.width:f.right-f.left,l=0<=f.left+.25*l&&f.left+.75*l<c;if(g=0<=f.top+.25*g&&f.top+.75*g<b&&l){f=r.elementFromPoint((f.left+f.right)/2,(f.top+f.bottom)/2);if(f===a)f=!0;else a:{if(f)for(f=f.parentNode;null!=f;){if(f==a){f=
!0;break a}f=f.parentNode}f=!1}g=f}if(g)return!0}return!1}function ia(){return Ja&&!h.opera?ba.clientHeight:O.clientHeight}function Wc(a,b){function c(b){var c=ja(a)["line-height"];"normal"==c?c=1.2*kc(ja(a)["font-size"]):/[a-z]+/im.test(c)?c=parseFloat(c):c=kc(ja(a)["font-size"])*parseFloat(c);return Math.ceil(c*b)}function e(b){var c=b.lastChild&&!b.lastChild.nodeValue&&b.lastChild.innerHTML?b.lastChild.innerHTML:b.lastChild.nodeValue;if(b.lastChild.children&&0<b.lastChild.children.length)return e(Array.prototype.slice.call(b.children).pop());
if(b.lastChild&&c&&""!=c&&c!=h.S)return b.lastChild;b.lastChild.parentNode.removeChild(b.lastChild);return e(a)}function d(b,c){if(c&&b){var g=!(b.nodeValue||!b.innerHTML),l=(g?b.innerHTML:b.nodeValue).replace(h.S,"");p||(0<m.length?k=m.shift():k="",p=l.split(k));1<p.length?(q=p.pop(),f(b,p.join(k),g)):p=null;if(p){if(a.clientHeight<=c)if(0<=m.length&&""!=k)f(b,p.join(k)+k+q,g),p=null;else return a.innerHTML}else""==k&&(f(b,"",g),b=e(a),m=h.ta.slice(0),k=m[0],q=p=null);return d(b,c)}}function f(a,
b,c){c?a.innerHTML=b+h.S:a.nodeValue=b+h.S}b=b||{};var h={za:b.clamp||2,ga:"undefined"!=typeof b.ga?b.ga:!0,ta:[".","-","\u2013","\u2014"," "],S:"\u2026"},g=a.style,l=h.za,m=h.ta.slice(0),k=m[0],p,q;"undefined"!=typeof a.style.webkitLineClamp&&h.ga?(g.overflow="hidden",g.textOverflow="ellipsis",g.webkitBoxOrient="vertical",g.display="-webkit-box",g.webkitLineClamp=l):(g=c(l),g<=a.clientHeight&&d(e(a),g))}function Xc(a,b,c){var e=b||1;if(Oa.length){for(var d in Oa.Ma)Oa.Ma.hasOwnProperty(d)&&$a(h,
"resize orientationchange",Oa[d]);Oa=[]}c.min=c.min||Number.NEGATIVE_INFINITY;c.max=c.max||Number.POSITIVE_INFINITY;y(a,function(){function a(){var d=Math.round(Math.max(Math.min(kc(ja(b).width)/(10*e),parseFloat(c.max)),parseFloat(c.min)));b.style.fontSize=d+z}var b=this;a();Oa.push(a);E(h,"resize orientationchange",a)})}function Tb(a){return Aa(a).top+v(a.offsetHeight)}function Aa(a){a.getBoundingClientRect?(a=a.getBoundingClientRect(),a={top:Math.round(a.top+(h.pageYOffset||r.scrollTop||O.scrollTop)-
(r.clientTop||O.clientTop||0)),left:Math.round(a.left+(h.pageXOffset||r.scrollLeft||O.scrollLeft)-(r.clientLeft||O.clientLeft||0))}):a=lc(a);return a}function Yc(){}function aa(a,b,c,e,d,f,k,g){g=g||h;d=d||r;a instanceof g.HTMLElement&&(f=l(f,!1),k=l(k,!0),d=H("iframe",d),d.id=a.id+"_frame",k&&(d.sandbox="allow-same-origin allow-scripts allow-popups allow-forms"),p(c)&&(d.style.width=c+z),p(e)&&(d.style.height=e+z),d.setAttribute("allowtransparency","true"),d.setAttribute("marginwidth","0"),d.setAttribute("marginheight",
"0"),d.setAttribute("hspace","0"),d.setAttribute("vspace","0"),d.setAttribute("frameborder","0"),d.setAttribute("scrolling","no"),a.appendChild(d),f?d.src=b:(a=d.contentDocument,a.open(),a.write(b),a.close()))}function Q(a,b,c){var e;e=e||h;c=c||r;if(a instanceof e.HTMLElement&&(a.innerHTML=b)&&(e=a.childNodes)&&e.length){b=[];for(var d=0;e[d];d++){var f=e[d];!f.nodeName||"script"!==f.nodeName.toLowerCase()||f.type&&"text/javascript"!==f.type.toLowerCase()||b.push(e[d])}for(var l in b){e=b[l].parentNode?
b[l].parentNode.removeChild(b[l]):b[l];var d=(d=c)||r,f=a||bb,g=H("script",d);g.type="text/javascript";if(p(e.src)&&e.src)g.src=e.src,g.className=e.className;else{var k=e.text||e.textContent||e.innerHTML||"";g.className=e.className;g.appendChild(d.createTextNode(k))}f.appendChild(g)}}}function wa(a){var b;b=b||r;var c=H("style",b);c.setAttribute("rel","stylesheet");c.setAttribute(Vb,"text/css");bb.appendChild(c);xa?c.styleSheet.cssText=a:c.appendChild(b.createTextNode(a))}function K(){}function kc(a){return parseFloat(a)}
function v(a){return parseInt(a,10)}function V(a,b){if(p(b)){var c;c=Math.pow(10,b);return Math.round(a*c)/c}return Math.round(a)}function Ec(a){return Math.floor(a)}function Z(){return(new Date).getTime()%1E7*100+V(99*Math.random())}function p(a){return"undefined"!=typeof a}function l(a,b){b=p(b)?b:!1;return p(a)?a:b}function eb(a){return p(a)?v(a):!1}function Bd(a,b){y(b,function(c){a[c]=b[c]})}function cb(a,b,c){c=c||r;return b?c.getElementsByTagName(a):c.getElementsByTagName(a)[0]}function Yb(a){return a.getAttribute("baseStyleRight")}
function Ya(a,b,c){a.setAttribute(b,c+"")}function y(a,b){for(var c in a)if(a.hasOwnProperty(c)&&"length"!==c&&!1===b.call(a[c],c,a[c]))break}function Cd(a){a=a.split("+").join(" ");for(var b={},c,e=/[?&]?([^=]+)=([^&]*)/g;c=e.exec(a);)b[decodeURIComponent(c[1])]=decodeURIComponent(c[2]);return b}function E(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var e=b.length,d;for(d=0;d<e;d++)y(a,function(){this.addEventListener?this.addEventListener(b[d],c,!1):
this.attachEvent("on"+b[d],c)})}}function $a(a,b,c){if(a){"[object NodeList]"!=Object.prototype.toString.call(a)&&(a=[a]);b=b.split(" ");var e=b.length,d;for(d=0;d<e;d++)y(a,function(){this.detachEvent?this.detachEvent("on"+b[d],c):(this.removeEventListener(b[d],c,!0),this.removeEventListener(b[d],c))})}}function db(a,b){b=b.split(" ");for(var c=0;c<b.length;c++)a.className=a.className.replace(new RegExp("\\b"+b[c]+"\\b","g"),"").replace(/\s+/g," ").replace(/(^ | $)/g,"")}function A(a,b){db(a,b);
b=b.split(" ");for(var c=0;c<b.length;c++)a.className+=" "+b[c];a.className=a.className.trim()}function Zb(a,b){return(new RegExp("\\b"+b+"\\b","im")).test(a.className)}function H(a,b){b=b||r;return b.createElement(a)}function ub(a,b,c){if(a.length)for(var e=a.length;e--;)a[e].style[b]=c}function dc(a){a=K("lx_block_params",a);var b=a.length,c=[];if(b)for(var e=0;e<b;e++)for(var d=a[e].attributes,f=d.length,h;f--;)h=d[f],0===h.name.indexOf("data-")&&(c[h.name.replace("data-","")]=h.value);return c}
function Zc(a){for(var b={},c=[],e=a.length,d=0,f=0;f<e;f++){var h=a[f];1!==b[h]&&(b[h]=1,c[d++]=h)}return c}function jc(a,b){if(null==a||"object"!==typeof a)return a;if(void 0==b)b=[];else{var c,e=b.length;for(c=0;c<e;c++)if(a===b[c])return a}b.push(a);if("function"==typeof a.clone)return a.clone(!0);if("[object Array]"==Object.prototype.toString.call(a)){e=a.slice();for(c=e.length;c--;)e[c]=jc(e[c],b);return e}if(a instanceof Date)return new Date(a.getTime());if(a instanceof RegExp)return new RegExp(a);
if(a.nodeType&&"function"==typeof a.cloneNode)return a.cloneNode(!0);c=Object.getPrototypeOf?Object.getPrototypeOf(a):a.__proto__;c||(c=a.constructor.prototype);var e=mc(c),d;for(d in a)e[d]=jc(a[d],b);return e}function T(a,b){b||(b=function(){});if((Bb||$c()&&ad)&&!/\bclickio\w*?\b/im.test(a)){if(Bb){var c="";try{c=h.top.location.href}catch(e){c=h.location.href}a+="&furl="+encodeURIComponent(c)}Dd(a,b)}else Sc(a,b)}function Ic(a,b){var c;b=b||ta();T(P+"luxupcdna.com/multishows/"+a+"/"+b,c||function(){})}
function Sc(a,b){b||(b=function(){});var c=H("script");c.setAttribute(Vb,"text/javascript");c.setAttribute("src",a);c.setAttribute("async","async");p(c)&&(xa?c.onreadystatechange=function(){"loaded"!=this.readyState&&"complete"!=this.readyState||setTimeout(b,0)}:c.onload=function(){setTimeout(b,0)},bb.appendChild(c))}function Dd(a,b){b||(b=function(){});var c="ws"+("https:"==h.top.location.protocol?"s":"");a=a.replace(P,c+"://");a=a.replace(/wss?:\/\/([a-zA-Z0-9-.]+)\//img,c+"://$1/ws/");var c=new Worker(URL.createObjectURL(new Blob(['var r=null,s=new WebSocket("'+
a+'");s.onmessage=function(e){if(e.data){postMessage(e.data);r=e.data;s.close();}};onmessage=function(e){if(e.data=="!"){close();};if(e.data=="?"&&r){postMessage(r);}}'],{type:"application/javascript"}))),e=setInterval(function(a){return function(){a.postMessage("?")}}(c),50);c.onmessage=function(a,b,c){return function(e){a.onmessage=function(){};clearInterval(c);a.postMessage("!");Ed(e);b()}}(c,b,e)}function Ed(a){a=a.data;var b=H("script");b.type="text/javascript";b.appendChild(r.createTextNode(a));
bb.appendChild(b)}function bd(){var a=!1,b=navigator,c=null;if(p(b.plugins)&&"object"==typeof b.plugins["Shockwave Flash"])!(c=b.plugins["Shockwave Flash"].description)||p(b.mimeTypes)&&b.mimeTypes["application/x-shockwave-flash"]&&!b.mimeTypes["application/x-shockwave-flash"].enabledPlugin||(c=c.replace(/^.*\s+(\S+\s+\S+$)/,"$1"),a=[0,0,0],a[0]=v(c.replace(/^(.*)\..*$/,"$1")),a[1]=v(c.replace(/^.*\.(.*)\s.*$/,"$1")),a[2]=/[a-zA-Z]/.test(c)?v(c.replace(/^.*[a-zA-Z]+(.*)$/,"$1")):0);else if(p(h.ActiveXObject))try{if(c=
(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))c=c.split(" ")[1].split(","),a=[v(c[0]),v(c[1]),v(c[2])]}catch(e){}return a=!1!==a?a.join("."):a}function Fd(){var a=bd(),b=["10","0","42"];if(!1===a)return!1;a=a.split(".");b[0]=parseInt(b[0],10);b[1]=parseInt(b[1],10)||0;b[2]=parseInt(b[2],10)||0;return a[0]>b[0]||a[0]==b[0]&&a[1]>b[1]||a[0]==b[0]&&a[1]==b[1]&&a[2]>=b[2]?a.join("."):!1}function $c(){if(null!==Fa)return Fa;var a="pub_300x250 pub_300x250m pub_728x90 text-ad textAd text_ad text_ads text-ads text-ad-links";
p(h.__lxG__.adbc)&&(a+=" "+h.__lxG__.adbc);var b=H("div");b.setAttribute("style","width: 1px !important; height: 1px !important; position: absolute !important; left: -10000px !important; top: -10000px !important; ");b.setAttribute("class",a);p(h.__lxG__.adbi)&&(b.id=h.__lxG__.adbi);O.appendChild(b);var a=!0,c=!1;p(h.__lxG__.adbh)?(b.innerHTML=h.__lxG__.adbh,p(h.__lxG__.adbhs)&&(c=b,b=b.querySelector(h.__lxG__.adbhs))):p(h.__lxG__.adbs)&&(a=!1,b=r.querySelector(h.__lxG__.adbs));Fa=!1;if(null!==O.getAttribute("abp")||
null===b.offsetParent||0==b.offsetHeight||0==b.offsetLeft||0==b.offsetTop||0==b.offsetWidth||0==b.clientHeight||0==b.clientWidth)Fa=!0;if(!Fa){var e=ja(b);if("none"==e.getPropertyValue("display")||"hidden"==e.getPropertyValue("visibility"))Fa=!0}a&&O.removeChild(b);c&&O.removeChild(c);return Fa}function ta(a){a=a||!1;var b="",b="?rt="+Z();r.referrer&&(b+="&r="+encodeURIComponent(r.referrer));ra&&(b+="&recurring=1");cd&&(b+="&flash="+encodeURIComponent(cd));xa&&(b+="&isie=1");"https:"==h.location.protocol&&
(b+="&https=1");Cb&&(b+="&md="+encodeURIComponent(Cb));b+="&f="+la;p(screen.width)&&(b+="&scr="+encodeURIComponent(screen.width+"x"+screen.height));p(h.innerWidth)&&(b+="&wnd="+encodeURIComponent(h.innerWidth+"x"+h.innerHeight));$c()&&(b+="&bl=1");dd&&(dd=!1,b+="&add=1");ca.X(gc())&&(b+="&ignorefloat=1");nc.length&&(b+="&ignore="+nc.join(";"));p(h.__lxG__.multishows_params)&&(b+=yc(h.__lxG__.multishows_params));X.start&&(b+="&pbjs=1");a&&(a=Gd(a))&&(b+="&bids="+encodeURIComponent(a));return b+=h[x].multishowsAdd?
"&"+h[x].multishowsAdd:""}function yc(a){var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+="&"+encodeURIComponent(c)+"="+encodeURIComponent(a[c]));return b}function ob(a){return p(a.getClientRects)&&(a=a.getClientRects())&&p(a[0])&&p(a[0].right)&&p(a[0].left)?(a=a[0],{width:V(a.right-a.left),height:V(a.bottom-a.top)}):!1}function Hd(a,b){return function(){if(b&&""!=b.innerHTML){var c=ob(b);c&&T(P+"luxupcdna.com/area_size/?data="+a+","+c.width+","+c.height,function(){})}}}function oc(a,b){b=b||!1;
var c=!1,e=!0,e=ed(l(a.check)),d=l(a.location),f=l(a.location_max);if(e&&d)for(f?f=v(f):f=1,e=null,1<f?e=r.querySelectorAll(d):e=[r.querySelector(d)],d=0;d<e.length&&!(d+1>f);d++){var h=e[d];if(h){var g=H("div");g.id=a.id;var k=1+d;g.setAttribute("data-cnt",k);g.className="__lxG__multi __lxG__multi_"+a.id;Sb({ids:[a.id+"."+k]},Ia,function(a){return function(b){b=b.ids;b.length&&a.setAttribute("data-cnt",b[0].cnt);return-1}}(g));b?(h.innerHTML="",h.appendChild(g)):h.parentNode.insertBefore(g,h.nextSibling)}c||
(c=g)}return c}function qb(a,b){var c=r.getElementById(a);if(b){var e=r.querySelectorAll("#"+a),d;for(d in e)if(e.hasOwnProperty(d)&&"length"!=d&&e[d].getAttribute("data-cnt")==b){c=e[d];break}}return c}function Db(a){var b=a.which?a.which:a.button;a=(xa?a.srcElement:a.target).nodeName.toLowerCase();"a"!=a&&"img"!=a||2==b||3==b||(clearTimeout(pc),pc=setTimeout(function(){pc=null;Eb()},500))}function fd(a){a=a||!1;var b=[],c=[];Fb&&y(F,function(a){a=a.substr(1);X.bidding&&(~X.bidding.indexOf(a)||!~(""+
a).indexOf(".")&&~X.bidding.indexOf(v(a)))?c.push(encodeURIComponent(a)):b.push(encodeURIComponent(a))});return a?[b.join(";"),c.join(";")]:b.join(";")}function Gd(a){a=a||fd();if(X.bids){var b=!1,c="";y(a.split(";"),function(a,d){~gd.indexOf(d)||(y(X.bids,function(a,e){if(e.id==d){if(e.bids.length){var g=[];y(e.bids,function(a,b){g.push(b.join("_"))});c+=g.join(",");b=!0}gd.push(d);return!1}}),c+="-")});if(b)return c=c.substring(0,c.length-1)}return""}function hd(a){id(a.target?a.target:a.srcElement)}
function Id(a){var b=/\/(i)\/(a??)(\d+?)\//m,c=b.exec(a);null==c&&(b=/\/(ii)\/(a??)(\d+?)\//m,c=b.exec(a));var e=!1,d=!1;null!=c&&16!=c[3]&&(e=v(c[3]),e=(2*(10*e+40)-40)/10,16<=e&&(e=16),d=10*e+40,e=a.replace(b,"/$1/$2"+e+"/"));return{url:e,size:d}}function jd(a){var b=v("CSS1Compat"!=r.compatMode||h.opera?O.scrollTop:ba.scrollTop),c=v(b+ia()),e=v("CSS1Compat"!=r.compatMode||h.opera?O.scrollLeft:ba.scrollLeft),d=v(e+(Ja&&!h.opera?ba.clientWidth:O.clientWidth)),f=a.getClientRects()[0],l=V(f.top)+b,
g=V(f.bottom)+b,k=V(f.left)+e,f=V(f.right)+e;l<b&&(a.style.top=v(a.style.top)+(b-l)+3+z);g>c&&(a.style.top=v(a.style.top)-(g-c)-3+z);k<e&&(a.style.left=v(a.style.left)+(e-k)+3+z);f>d&&(a.style.left=v(a.style.left)-(f-d)-3+z)}function lc(a){for(var b=0,c=0;a&&"relative"!=ja(a).position&&ja(a).position!=vb;)b+=v(a.offsetTop),c+=v(a.offsetLeft),a=a.offsetParent;return{top:b,left:c}}function ja(a){return a.La=a.La||a.currentStyle||getComputedStyle(a,0)}function Jd(a){return function(){a&&a.parentNode&&
a.parentNode.removeChild(a)}}function id(a){var b,c=lc(a),e=Id(a.src),d=e.size;if((e=e.url)&&e!=a.src){a.previousSibling&&"img"==a.previousSibling.nodeName.toLowerCase()?b=a.previousSibling:(b=a.cloneNode(!1),xa&&b.detachEvent("onmouseover",hd),b.style.position=vb,b.style.top=Gb,b.style.left=Gb,b.style.margin=0+z,b.style.maxWidth="",b.style.maxHeight="",E(b,"mouseout",function(){clearTimeout(~~b.getAttribute("enlrgTmr"));Ya(b,"shrTmr",setTimeout(function(){kd(b,a)},10))}),a.parentNode.insertBefore(b,
a));if(b.src==a.src){var f=b.cloneNode(!1);E(f,"load",function(){b.src=f.src;setTimeout(Jd(f),250)});f.src=e;b.parentNode.insertBefore(f,b)}b.width=a.width;b.height=a.height;b.style.top=c.top+z;b.style.left=c.left+z;a.style.visibility="hidden";a.parentNode.style.zIndex=1E5;jd(b);b.setAttribute("enlrgTmr",setTimeout(function(){ld(b,d)},10))}}function kd(a,b){clearTimeout(~~a.getAttribute("enlrgTmr"));var c=lc(b),e=v(a.height)-10;a.width=v(a.width)-10;a.height=e;e=v(c.left)>v(a.style.left)?v(a.style.left)+
5:v(a.style.left)-5;a.style.top=(v(c.top)>v(a.style.top)?v(a.style.top)+5:v(a.style.top)-5)+z;a.style.left=e+z;v(a.width)>v(b.width)?a.setAttribute("shrTmr",setTimeout(function(){kd(a,b)},10)):(a.style.top=Gb,a.style.left=Gb,b.style.visibility="",b.parentNode.style.zIndex="")}function ld(a,b){clearTimeout(~~a.getAttribute("shrTmr"));var c=v(a.height)+10;a.width=v(a.width)+10;a.height=c;c=v(a.style.left)-5;a.style.top=v(a.style.top)-5+z;a.style.left=c+z;jd(a);v(a.width)<b&&a.setAttribute("enlrgTmr",
setTimeout(function(){ld(a,b)},10))}function gc(){return"_lxretpopupignore"}function ed(a){var b=!1;if(!1===a)return b;try{b=null!==r.querySelector(a)}catch(c){}return b}function qc(a,b,c){Pa=!0;b&&(a?(r.write('<script type="text/javascript" language="JavaScript" src="'+P+"luxupcdna.com/multishows/"+b+"/"+ta()+'">\x3c/script>'),Pa=!1):T(P+"luxupcdna.com/multishows/"+b+"/"+ta(b),function(){Pa=!1}));c&&(Hb&&clearInterval(Hb),Hb=setInterval(function(a){return function(){var b=(new Date).getTime(),
c=!X.bidding;if(b>X.start+Ib&&b<X.start+Ib+100||c)Yc("Bidding:\n   started: "+(new Date(X.start)).toISOString()+"\n   ended: "+(new Date(X.end)).toISOString()),clearInterval(Hb),Pa=!0,T(P+"luxupcdna.com/multishows/"+a+"/"+ta(a),function(){Pa=!1})}}(c),50))}function Eb(a){if(!Pa){var b=fd(!0),c=b[0],b=b[1];if(!ib&&(c||b)&&!rc){var e=c.split(";"),d=b.split(";"),f=e.concat(d);y(f,function(a){~md.indexOf(f[a])&&f.splice(a,1)});if(f.length){md=f;rc=!0;sc=function(a,b,c){return function(d){d=d||[];rc=
jb=!1;var e=[],f=[];y(b,function(a,b){~d.indexOf(""+b)||e.push(b)});y(c,function(a,b){~d.indexOf(""+b)||f.push(b)});qc(a,e.join(";"),f.join(";"))}}(a,e,d);Ma("getPreloadItems",{ids:f},Kd);jb=setTimeout(sc,100);return}}qc(a,c,b)}}var F=k,r=document,h=window,O=r.body,ba=r.documentElement,bb=function(a){a=a||r;html=a.documentElement;var b=cb("head",!1,a);if(b)return b;for(b=html.firstChild;b&&"#text"==b.nodeName.toLowerCase();)b=b.nextSibling;if(b&&"#text"!=b.nodeName.toLowerCase())return b;a=H("head",
a);html.appendChild(a);return a}(),ka=navigator.userAgent.toLowerCase(),Ld=(navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[])[1],Ja="CSS1Compat"===r.compatMode,Bb=/yabrowser/.test(ka),ad=/chrome/.test(ka)&&!Bb,Za=ad||Bb,Jb=/opera/.test(ka),xa=/msie/.test(ka)&&!Jb,Md=!window.ActiveXObject&&"ActiveXObject"in window,K=r.getElementsByClassName?function(a,b){return(b||document).getElementsByClassName(a)}:function(a,b){b=b||document;var c=b.getElementsByTagName("*"),e=c.length,
d=a.split(/\s+/),f=d.length,h=[],g,l;for(g=0;g<e;g++)for(l=0;l<f;l++)if(~c[g].className.search("\\b"+d[l]+"\\b")){h.push(c[g]);break}return h},mc=Object.create;"function"!==typeof mc&&(mc=function(a){function b(){}b.prototype=a;return new b});var pb=v(f),x="__lxG"+pb+"__",Kb={},ra=!1,Pa=!1,pc=null,Fb=0,Ea=[],Na=null,cd=Za?Fd():bd(),Mc="bottom",z="px",Gb="-100000"+z,vb="absolute",I={},Vb="type",Y="",nd=!1,La="scroll",fa="click",fb="ios",R="android",wb=xa&&(!Ja||8>v(Ld)&&Ja),P="http"+("about:"==h.location.protocol?
"https:"==h.top.location.protocol?"s":"":"https:"==h.location.protocol?"s":"")+"://",fc=P+"luxupcdna.com/real_show_log/?data=",Cb=!1,tc="__lx"+pb,Wb=tc+"_load_cnt",Fc=tc+"_load_tmr",Gc=tc+"_load_tmr_pre",od=!1,Hb=!1,Ib=3E3,dd=!0,uc=5,vc=null,nc=[],Fa=null,Oa=[],ca={get:function(a,b){var c;this.X(a)?(c=r.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"),c=decodeURIComponent(c)||(p(b)?b:null)):c=p(b)?b:null;return c},
set:function(a,b,c,e,d,f){if(!a||/^(?:expires|max\-age|path|domain|secure)$/i.test(a))return!1;var h="";if(c)switch(c.constructor){case Number:h=Infinity===c?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+c;break;case String:h="; expires="+c;break;case Date:h="; expires="+c.toUTCString()}r.cookie=encodeURIComponent(a)+"="+encodeURIComponent(b)+h+(d?"; domain="+d:"")+(e?"; path="+e:"")+(f?"; secure":"");return!0},Wa:function(a,b,c){if(!a||!this.Xa(a))return!1;r.cookie=encodeURIComponent(a)+
"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(c?"; domain="+c:"")+(b?"; path="+b:"");return!0},X:function(a){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(a).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(r.cookie)},list:function(){for(var a=r.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/),b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);return a}};E(h,La,Vc);Kb[x]={};Kb[x].sa=function(a){if(!Y)return!0;a=a||h.event;var b=(a.target||a.srcElement).nodeName.toLowerCase();
if(xa&&"a"==b)return!0;Y+="?rnd="+Z()+(h[x].Ka?"&"+h[x].Ka:"");Jb?(h.open(Y,x+"popunder","resizable=1,toolbar=1,location=1,menubar=1,status=1,directories=0,width="+screen.availWidth+",height="+screen.availHeight),h.blur(),h.focus()):Za?yd(Y,a):xa?Uc(Y):Md?zd(Y):setTimeout(function(){Uc(Y)},0);$a(O,Za||Jb?"mousedown":fa,Kb[x].sa);return!0};var ib=null;p(h[x])||(h[x]={});p(h[x].instances)||(h[x].instances=[]);p(h[x].blocks)||(h[x].blocks={});var X={bidding:!1,start:0,end:0,bids:!1},Qa=Z(),la=x+Qa;h[la]=
{};h[x].instances.push(Qa);p(h.__lxG__)||(h.__lxG__={});Ib=l(h.__lxG__.biddingBlocksDelay,Ib);p(h[x].closed)||(h[x].closed=function(){},h[x].clicked=function(){});p(h[x].popunderShow)||(h[x].popunderShow=!1);p(h[x].allLoaded)||(h[x].allLoaded=function(){});p(h[x].popunderAdd)||(h[x].popunderAdd="");p(h[x].multishowsAdd)||(h[x].multishowsAdd="");var pd=x,qd=x+"cache",wc=la,rd=h.frameElement&&h.frameElement.id&&0===h.frameElement.id.indexOf("google_ads_iframe_"),Ab=[wc,pd,qd],ya=[h.location.hostname],
Ab=Ab||["postMessageApiPrefix"],ya=ya||[window.location.hostname],ic="sender"+Z(),hb=[],gb={},ga=[],Lb=[];E(h,"message",function(a){a.data&&p(a.data.indexOf)&&0===a.data.indexOf("__")&&Yc("from "+a.origin.replace(/https?:\/\//img,""));if(a.data&&(~ya.indexOf(a.origin.replace(/https?:\/\//img,""))||~ya.indexOf("*"))){if(!p(a.data.indexOf))return!1;var b=!1,c="";y(Ab,function(d,e){if(0===a.data.indexOf(e+"|"))return c=e,b=!0,!1});if(!b)return!1;var e=null;try{e=JSON.parse(a.data.replace(c+"|",""))}catch(g){return!1}if(l(e.type)){if(l(e.sender_id)==
ic)return!1;if("subscribe"==e.type){var d=!1,f=Zc(l(e.subscriber.events,["*"])),h=l(e.subscriber.eventsParams,{});y(ga,function(b){if(ga[b].Ua===a.source)return d=!0,ga[b].o=Zc(ga[b].o.concat(f)),Bd(ga[b].K,h),!1});d||ga.push({ea:yb(a.source,a.origin,e.subscriber.prefix),o:f,K:h})}"event"!=e.type||~Lb.indexOf(e.rnd)||~Lb.indexOf(l(e.source_rnd))||(Lb.push(e.rnd),l(e.source_rnd)&&Lb.push(e.source_rnd),xd(a,e,c),e.broadcast&&wd(e.event_type,e.event,l(e.source_rnd,l(e.rnd,0))))}}});var Ia=yb(h.top,h.top===
h.self?h.location.protocol+"//"+h.location.hostname:"*",pd),Kd=yb(h.top,h.top===h.self?h.location.protocol+"//"+h.location.hostname:"*",qd);va("renderOver",function(a){if(rd){var b=a.data[0],c=h.frameElement.parentNode.parentNode,e=c.parentNode,d=h.parent,f=d.document||d.contentDocument||d.contentWindow.document;wa(b.style);d=f.createElement("div");d.id=b.div_name;Q(d,b.source,f);c.style.display="none";e.insertBefore(d,c);N(b,f);y(a.data,function(a,b){if("counters"==b.type)return N(b,f),!1})}else{if(b=
qb(l(a.data[0].div_name),l(a.data[0].sub_id)))b.innerHTML="";setTimeout(function(){h[la].parser(a.data)},0)}});va("renderBidderOver",function(a){var b=a.data[0],c=b.id,e=l(b.sub_id);if(!p(F["_"+(c+(e?"."+e:""))]))return!1;a=a.num;var d=Z();if(rd){var e=h.frameElement.parentNode.parentNode,f=h.parent,k=f.document||f.contentDocument||f.contentWindow.document;va("bidHtml",function(a,b,c,e,f){return function(h){if(h.rnd==d){var k=l(a.sub_id),p=f.createElement("div");p.id=a.div_name;k&&p.setAttribute("data-cnt",
k);k=b.getAttribute("style");Ya(b,"style",(k?k+";":"")+"display: none !important;");c.insertBefore(p,b);h.html&&!h.url?aa(p,h.html,h.w,h.h,f,!1,l(a.use_sandbox),e):!h.html&&h.url&&aa(p,h.url,h.w,h.h,f,!0,l(a.use_sandbox),e);N(a,f);y(h.data,function(a,b){if("counters"==b.type)return N(b,f),!1});return-1}}}(b,e,e.parentNode,f,k))}else va("bidHtml",function(a){return function(b){if(b.rnd==d){var c=a.div_name,e;if(l(a.sub_id)){var f=l(a.sub_id),h=r.querySelectorAll("#"+c);y(h,function(a){if(h[a].getAttribute("data-cnt")==
f)return e=h[a],!1})}else e=r.querySelector("#"+c);e.innerHTML="";b.html&&!b.url?aa(e,b.html,b.w,b.h,k):!b.html&&b.url&&aa(e,b.url,b.w,b.h,k,!0);N(a,k);y(b.data,function(a,b){if("counters"==b.type)return N(b,k),!1});return-1}}}(b));Ma("getBidHtml",{id:c,num:a,rnd:d},Ia)});va("codePing",function(a,b){Ma("codePong",{},b)});zb("subscribe",{subscriber:{prefix:wc,events:["renderOver","renderBidder","renderBidderOver"]}},Ia,!0);var Da=null,ud=["cfg","params","get_area_size"],vd=["counters","iframe_counters"],
hc=[];h[la].addPreload=function(a){var b=[];y(a,function(a,e){F[a]=e;b.push(a.replace("_",""))});qc(0,b.join(";"),"")};va("getPreloadItems",function(a,b){if(!ib||!Da)return!1;var c=a.ids,e=!1,d=JSON.parse(JSON.stringify(hc)),f=[];y(c,function(a,b){l(Da[b])&&(e=!0,d.push(Da[b]),f.push(b))});e&&(y(f,function(a,b){delete Da[b]}),Ma("preloadItems",{preloadItems:d,found:f},b))});h[la].parser=h[x].parser=function(a){Ea=[];var b=!1,c={},e={},d;for(d in a)a.hasOwnProperty(d)&&(g=a[d],l(g.sub_id)&&(b=!0),
"params"==g.type?(c=l(g.site,{}),e=l(g.blocks,[]),l(c.ch_dmn)&&(~ya.indexOf(c.ch_dmn)||ya.push(c.ch_dmn)),y(e,function(a,b){p(b.ch_dmn)&&!~ya.indexOf(b.ch_dmn)&&ya.push(b.ch_dmn)})):"cfg"==g.type&&(od=l(g.isMobile)&&ea())&&uc&&!vc&&(vc=setInterval(function(){return function(){uc?(uc--,q()):clearInterval(vc)}}(),3E3)));var f=!1;y(a,function(b){var c=a[b];if(l(c.id)){var d=l(c.sub_id);b="_"+c.id;c=d?"_"+c.id+"."+d:!1;if(1==l((c?l(F[c]):l(F[b])).preload))f=!0;else return f=!1}});for(var k in a)if(a.hasOwnProperty(k)){var g=
a[k];if("params"!=g.type&&"cfg"!=g.type)if(!f&&"counters"==g.type){if(g.hasOwnProperty("urls"))for(var w=0;w<g.urls.length;w++)H("img").src=g.urls[w]+"&_lxrnd_="+Z()}else if(!f&&"iframe_counters"==g.type){if(g.hasOwnProperty("sources"))for(w=0;w<g.sources.length;w++)c=g.sources[w],d=H("iframe"),d.id="__lxG__frame_tracker_"+w,d.sandbox="allow-same-origin allow-scripts allow-forms",d.style.width=1+z,d.style.height=1+z,d.setAttribute("allowtransparency","true"),d.setAttribute("marginwidth","0"),d.setAttribute("marginheight",
"0"),d.setAttribute("hspace","0"),d.setAttribute("vspace","0"),d.setAttribute("frameborder","0"),d.setAttribute("scrolling","no"),d.src="javascript:'"+(c+"").replace(/[\\"']/g,"\\$&").replace(/\u0000/g,"\\0")+"'",O.appendChild(d)}else if(f||"get_area_size"!=g.type){if("mdcheck"==g.type)return g.hasOwnProperty("url")&&T(P+g.url+(~g.url.indexOf("?")?"&":"?")+"f="+la),!0;if("mdparam"==g.type)return g.hasOwnProperty("param")&&(Cb=g.param,g.hasOwnProperty("alg")&&g.alg&&(fc=P+g.alg+".luxupcdna.com/real_show_log/?data="),
b=l(g.incoming_params),k=l(g.incoming_ids),b&&k?(b+="&md="+encodeURIComponent(Cb),b=b.replace(/(^rt=)\d+?(&)/mg,"$1"+Z()+"$2"),setTimeout(function(a,b){return function(){Ic(a,b)}}(k,b),0)):setTimeout(function(){Eb(0)},0)),!0;if(!f&&l(g.id)&&(c=l(g.sub_id),d="_"+g.id,w=c?"_"+g.id+"."+c:!1,!(!w&&p(h[x].blocks[d])&&h[x].blocks[d]!=Qa||w&&p(h[x].blocks[w])&&h[x].blocks[w]!=Qa))){p(h[x].blocks[d])||(h[x].blocks[d]=Qa);var m=w?l(F[w]):l(F[d]);if(!m)p(e[g.id])?m=e[g.id]:m={},F[w?w:d]=m;else if(p(e[g.id])){var B=
["refresh_limit"];y(e[g.id],function(a){~B.indexOf(a)&&p(m[a])||(m[a]=e[g.id][a])})}if(p(m.debug)&&m.debug&&(d=!1,r.location.search?(w=Cd(r.location.search),p(w.lx_debugmode)&&1==w.lx_debugmode||(d=!0)):d=!0,d))continue;if(!p(m.location)&&r.getElementById(m.id)&&!r.getElementById(g.div_name)){d=r.querySelectorAll("#"+m.id);for(var J in d)d.hasOwnProperty(J)&&"length"!=J&&d[J].setAttribute("id",g.div_name)}m.id=g.div_name;p(m.location)||r.getElementById(m.id)||(d=document.createElement("div"),d.setAttribute("id",
m.id),O.appendChild(d));if(p(m)&&p(g.source)){d=qb(m.id,c);!1===Ca&&(Ca=p(g.isTablet)?v(g.isTablet):0);if(d&&"html"==g.type&&"exit"!=l(m.type)&&"native"!=l(m.type)&&g.source){ra||(wa(g.style),E(d,"click",Db));d.innerHTML=g.source;m.C=!0;var G=dc(d);m.wa=G;p(g.real_show_log)&&g.real_show_log&&Ea.push([d,g.real_show_log]);if(l(G.lxm_responsive)){var A=d.querySelectorAll(".lx_anons"),w=0,w=function(a,b){return function(){Xc(a,l(b.lxm_fit_factor,1.5),{min:l(b.lxm_fit_min,14)+z,max:l(b.lxm_fit_max,20)+
z});y(a,function(a,c){Wc(c,{clamp:l(b.lxm_clamp)})})}}(A,G);setTimeout(w,50);setTimeout(w,250);setTimeout(w,500);setTimeout(w,1E3);setTimeout(w,2E3)}if(p(m.zoomImages)&&m.zoomImages)for(w=d.getElementsByTagName("img"),G=w.length,A=0;A<G;A++)r.addEventListener?w[A].addEventListener("mouseover",function(){id(this)},!1):w[A].attachEvent("onmouseover",hd);N(g);pa(m,c)}d&&"exit"==l(m.type)&&g.source&&(d.style.display="none",ra||(wa(g.style),E(d,"click",Db)),d.innerHTML=g.source,G=dc(d),m.wa=G,A=d.querySelectorAll(".lx_anons"),
w=0,w=function(a,b){return function(){Xc(a,l(b.lxm_fit_factor,1.5),{min:l(b.lxm_fit_min,14)+z,max:l(b.lxm_fit_max,20)+z});y(a,function(a,c){Wc(c,{clamp:l(b.lxm_clamp)})})}}(A,G),setTimeout(w,1E3),ha(g,m,d));d&&"pu"==g.type&&!nd&&(g.hasOwnProperty("url")?Y=g.url:Y=P+"s.luxupcdna.com/pu/"+g.id+".html",g.hasOwnProperty("pattern")&&g.hasOwnProperty("timeout")?(w=ca.get(Fc,0),(new Date).getTime()-w>6E4*g.timeout&&da(1),w=v(ca.get(Wb,0)),~g.pattern.indexOf(w)||~g.pattern.indexOf(7)&&7<=w||(Y=!1)):Y=!1,
Y&&(E(O,Za||Jb?"mousedown":"click",Kb[x].sa),m.C=!0),nd=!0);if(("js"==g.type||"iframe"==g.type&&"js_npm"==l(m.type))&&"native"!=l(m.type)&&(w=!1,G=l(m.ai_mode),m.P=od&&!l(g.mobATF)&&!l(g.isTablet),"js_npm"==l(m.type)&&l(m.check)&&l(m.location)&&!c&&(d&&(w=d.getAttribute("data-cnt")?d.getAttribute("data-cnt"):1,d.parentNode.removeChild(d)),G?(d=ed(m.check),d||(m.R=l(m.R,0),10>m.R&&(m.R||(m.Na=function(a,b,c){return function(){a[b].parser([c])}}(h,la,g)),setTimeout(m.Na,1E3),m.R++))):d=oc(m)),d)){ra||
(p(g.style)&&wa(g.style),G||E(d,"click",Db));!c&&l(m.add_meta)&&za("width=device-width,initial-scale=1.0,maximum-scale=2.0,user-scalable=1");if(G&&!c){if(G=!p(m.c))m.c={H:!1,m:null,F:null,I:[]};m.c.source=g.source;m.c.Oa=g.type;m.c.ma=l(m.inject_pre_process);m.c.qa=l(g.pre_source);m.c.width=l(g.width);m.c.height=l(g.height);m.c.Pa=l(g.use_sandbox);m.c.counters=l(g.counters,[]);m.c.id=g.id;if(G)C(m,!1,w),m.c.ra=function(a){return function(){!a.c.H&&Ga(a)&&C(a);h.innerHeight+h.scrollY>=(ba&&ba.scrollHeight||
O.scrollHeight)&&$a(window,"scroll",a.c.ra)}}(m),E(window,"scroll",m.c.ra);else if(d=qb(m.id,c))m.P&&ia()>Aa(d).top?(w=n(d,g.source))?(Q(d,w),N(g),pa(m,c),u(d,{id:g.id,type:"npm_resized"})):u(d,{id:g.id,type:"npm"}):("iframe"==g.type?(p(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0))):Q(d,g.source),N(g),pa(m,c));!l(m.ai_clone_source)&&m.c.m.length&&Ga(m)&&(m.c.source=!1,C(m,!0))}else if(!l(m.ai_clone_source)&&(m.P&&ia()>Aa(d).top?(w=n(d,g.source))?(Q(d,w),
N(g),pa(m,c),u(d,{id:g.id,type:"npm_resized"})):u(d,{id:g.id,type:"npm"}):("iframe"==g.type?(p(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0))):Q(d,g.source),N(g),pa(m,c)),G=r.querySelectorAll("#"+m.id),!c&&(!b||l(m.location))&&G&&1<G.length))for(A=G.length;A;)d=G[A-1],1<G[A-1].getAttribute("data-cnt")&&(m.P&&ia()>Aa(d).top?(w=n(d,g.source))?(Q(d,w),N(g),pa(m,c),u(d,{id:g.id,type:"npm_resized"})):u(d,{id:g.id,type:"npm"}):("iframe"==g.type?(p(g.pre_source)&&
Q(d,g.pre_source),aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0))):Q(d,g.source),N(g),pa(m,c))),A--;m.C=!0}"js"!=g.type&&"iframe"!=g.type&&"html"!=g.type||"native"!=l(m.type)||(l(m.check)&&l(m.location)&&(d&&d.parentNode.removeChild(d),d=oc(m,!0)),d&&(ra||p(g.style)&&wa(g.style),"iframe"==g.type?(p(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0))):Q(d,g.source),N(g),m.C=!0));if("iframe"==g.type&&"js_npm"!=l(m.type)){if(l(m.check)||l(m.location))d&&
d.parentNode.removeChild(d),d=oc(m);ra||p(g.style)&&wa(g.style);p(g.pre_source)&&Q(d,g.pre_source);if(d){aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0));N(g);pa(m,c);G=r.querySelectorAll("#"+m.id);if((!b||l(m.location))&&G&&1<G.length)for(A=G.length;A;)d=G[A-1],1<G[A-1].getAttribute("data-cnt")&&(p(g.pre_source)&&Q(d,g.pre_source),aa(d,g.source,g.width,g.height,r,!1,l(g.use_sandbox,!0)),N(g),pa(m,c)),A--;m.C=!0}}d&&"float"==g.type&&(w=!1,ra||(wa(g.style),E(d,fa,Db)),c=g.id,p(I[c])||(I[c]=
F["_"+c],I[c].N=c,I[c].a=d,I[c].B=!1,I[c].G=!1,I[c].O=!1,I[c].l=0,I[c].u=!1,I[c].aa=!1,I[c].ba=!1,I[c].L=!1,p(g.real_show_log)&&g.real_show_log&&(I[c].aa=!0,I[c].ba=g.real_show_log),w=!0),I[c].a.innerHTML=g.source,I[c].a.style[I[c].side]=-1E3+z,I[c].a.style.display="block",I[c].width=v(I[c].a.width?I[c].a.width:I[c].a.offsetWidth),I[c].a.style[I[c].side]=-I[c].width+z,Qb(I[c],w),I[c].u&&(I[c].u=!1),Rc(I[c])(),m.C=!0,N(g));d&&"mobile"==g.type&&(G=!1,ra||wa(g.style),c=g.id,p(W[c])||(W[c]=F["_"+c],W[c].N=
c,W[c].a=d,W[c].G=!1,W[c].l=0,W[c].u=!1,G=!0),d.innerHTML=g.source,m.C=!0,Mb(W[c],G),W[c].u&&(W[c].u=!1),N(g));g.hasOwnProperty("iframe_source")&&(aa(d,g.iframe_source,1,1),N(g));"inlinevideo"==g.type&&sa(r.querySelector(l(m.location)),{Sa:g.video_url,ia:g.click_url,Ra:g.video_start_url,ua:g.video_end_url,J:l(g.video_trackers,!1),Ta:g.width,Qa:g.height,pa:l(g.overlay_html,""),ja:l(g.full_view_percent,100),V:l(m.width),ya:l(m.style),Ba:l(m.hideClose),Ca:l(m.hideMarker),ka:l(m.hidePostblock)})}}}else if(g.hasOwnProperty("ids"))for(c=
0;c<g.ids.length;c++)d=g.ids[c],p(F["_"+d])&&setTimeout(Hd(d,r.getElementById(F["_"+d].id)),3E3)}if(f){var K=[];y(a,function(b){b=a[b];if(l(b.id)){var c=l(b.sub_id),d="_"+b.id,c=c?"_"+b.id+"."+c:!1;1==l((c?l(F[c]):l(F[d])).preload)&&K.push(b)}else K.push(b)});Rb(a);return!0}for(var L in F)F.hasOwnProperty(L)&&!p(F[L].C)&&p(F[L].cap)&&F[L].cap();ra=!1;setTimeout(function(){h[x].allLoaded()},0);Vc()};var gd=[],fa="click",La="scroll",R="android",fb="ios",Mc="bottom",vb="absolute",W={},Nc=!1,sb=!1,tb=
!1,Ca=!1,$b=1,Jc=1,Kc=1,cc=0,bc=0,ac=!1,rb=-1,z="px",Xb=!1,Dc=!1,Ka=[],oa=[],ab=[],rc=!1,md=[],sc=!1,jb=!1;va("preloadItems",function(a){jb&&(clearTimeout(jb),jb=!1,setTimeout(function(){h[la].parser(a.preloadItems)},0),setTimeout(function(){sc(a.found)},0))});da(v(ca.get(Wb,0))+1);(function(){var a=!1;p(h.__lxG__.multishows_params)&&p(h.__lxG__.multishows_params.singleton)&&(a=h.__lxG__.multishows_params.singleton);y(F,function(b){var c=!1;a&&a!=b.replace("_","")&&(c=!0);var f=r.getElementById(F[b].id);
!0===l(F[b].preload)?(f=!0,null===ib&&(ib=!0)):ib=!1;c||"float"!=l(F[b].type)||ca.X(gc())&&(c=!0);!f||c?delete F[b]:Fb+=1});var b=ca.list(),c;for(c in b)b.hasOwnProperty(c)&&0===b[c].indexOf("_lxblockignore_")&&nc.push(b[c].replace("_lxblockignore_",""));Fb&&y(F,function(a){a in h[x].blocks?delete F[a]:!0!==l(F[a].preload)&&(h[x].blocks[a]=Qa)})})();var xc=[];y(F,function(a){xc.push(a.replace("_",""))});va("bids",function(a){X=a});zb("subscribe",{subscriber:{prefix:wc,events:["bids"],eventsParams:{bids:{ids:xc}}}},
Ia,!0);zc("getBids",{ids:xc},Ia,function(a){X=a;Eb(0)},function(){Eb(0)});return la}var da=document,n=window,kb=document,lb=window;(function(f){f=f||kb;html=f.documentElement;var k;k=f||kb;if(k=k.getElementsByTagName("head")[0])return k;for(k=html.firstChild;k&&"#text"==k.nodeName.toLowerCase();)k=k.nextSibling;if(k&&"#text"!=k.nodeName.toLowerCase())return k;f=f||kb;f=f.createElement("head");html.appendChild(f);return f})();var Ob=navigator.userAgent.toLowerCase();navigator.userAgent.toLowerCase().match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/);
var Wa=Object.create;"function"!==typeof Wa&&(Wa=function(f){function k(){}k.prototype=f;return new k});n.__lxGc__=n.__lxGc__||{s:{},b:0};n.__lxGp__=n.__lxGp__||{s:{}};if(n.__lxGc__.f)return setTimeout(n.__lxGc__.f,0),!1;var sa=["__lxGc__"],ea=[window.location.hostname],sa=sa||["postMessageApiPrefix"],ea=ea||[window.location.hostname],Ta="sender"+Ua(),za=[],ha={},M=[],Ra=[];(function(f,k,q){if(f){"[object NodeList]"!=Object.prototype.toString.call(f)&&(f=[f]);k=k.split(" ");var u=k.length,n;for(n=
0;n<u;n++)C(f,function(){this.addEventListener?this.addEventListener(k[n],q,!1):this.attachEvent("on"+k[n],q)})}})(lb,"message",function(f){f.data&&U(f.data.indexOf)&&0===f.data.indexOf("__")&&Rb("from "+f.origin.replace(/https?:\/\//img,""));if(f.data&&(~ea.indexOf(f.origin.replace(/https?:\/\//img,""))||~ea.indexOf("*"))){if(!U(f.data.indexOf))return!1;var k=!1,q="";C(sa,function(n,u){if(0===f.data.indexOf(u+"|"))return q=u,k=!0,!1});if(!k)return!1;var n=null;try{n=JSON.parse(f.data.replace(q+"|",
""))}catch(Ga){return!1}if(J(n.type)){if(J(n.sender_id)==Ta)return!1;if("subscribe"==n.type){var ma=!1,B=Va(J(n.subscriber.events,["*"])),S=J(n.subscriber.eventsParams,{});C(M,function(k){if(M[k].Ua===f.source)return ma=!0,M[k].o=Va(M[k].o.concat(B)),Sb(M[k].K,S),!1});ma||M.push({ea:Ha(f.source,f.origin,n.subscriber.prefix),o:B,K:S})}"event"!=n.type||~Ra.indexOf(n.rnd)||~Ra.indexOf(J(n.source_rnd))||(Ra.push(n.rnd),J(n.source_rnd)&&Ra.push(n.source_rnd),Qb(f,n,q),n.broadcast&&Pb(n.event_type,n.event,
J(n.source_rnd,J(n.rnd,0))))}}});var mb={},Sa={};n.__lxGc__.f=function(){if(!U(da.body)||!da.body)return!1;C(n.__lxGp__.s,function(f){var q=J(n.__lxGp__.s[f].b,[]);if(q.length){q=S(q);n.__lxGp__.s[f].b=[];var u={};C(q,function(f){f=q[f];var k;k=U(Sa[f])?++Sa[f]:1;Sa[f]=k;u[1<k?f+"."+k:f]={preload:!0}});J(mb[f])?n[mb[f]].addPreload(u):mb[f]=Xa(f.replace("_",""),u)}});if(n.__lxGc__.b&&n.__lxGc__.b!==n.__lxGc__["b`"]){n.__lxGc__["b`"]=n.__lxGc__.b;n.__lxGc__["s`"]?C(n.__lxGc__.s,function(f){n.__lxGc__["s`"][f]?
C(n.__lxGc__.s[f].b,function(q){n.__lxGc__["s`"][f].b[q]?(n.__lxGc__["s`"][f].b[q].i=n.__lxGc__.s[f].b[q].i,n.__lxGc__["s`"][f].b[q].ver=n.__lxGc__["s`"][f].b[q].ver||0,n.__lxGc__["s`"][f].b[q].ver++):(n.__lxGc__["s`"][f].b[q]=S(n.__lxGc__.s[f].b[q]),n.__lxGc__["s`"][f].b[q].ver=0)}):n.__lxGc__["s`"][f]=S(n.__lxGc__.s[f])}):n.__lxGc__["s`"]=S(n.__lxGc__.s);var f=da.querySelectorAll(".__lxGc__");if(!f.length)return!1;C(n.__lxGc__["s`"],function(k){var q=0,u={},J={},B="__lxG"+k.replace("_","")+"__",
M=Ha(lb.top,"*",B);~sa.indexOf(B)&&sa.push(B);C(n.__lxGc__["s`"][k].b,function(B){var L=n.__lxGc__["s`"][k].b[B];if(!L._d||U(L.cnt)&&L.cnt!=L.i+1){n.__lxGc__["s`"][k].b[B]._d=!0;L.id=L.id||"lx"+B;L.cnt=L.cnt||0;var M=new RegExp("\\[(?:'|\")b(?:'|\")\\]\\[(?:'|\")"+B+"(?:'|\")\\]","im");C(f,function(k){if((M.test(f[k].text)||"div"===f[k].nodeName.toLowerCase()&&f[k].nextElementSibling&&"script"===f[k].nextElementSibling.nodeName.toLowerCase()&&M.test(f[k].nextElementSibling.text)||"div"===f[k].nodeName.toLowerCase()&&
f[k].getElementsByTagName("script").length&&M.test(f[k].getElementsByTagName("script")[0].text))&&!f[k].getAttribute("data-cnt")){f[k].setAttribute("data-cnt",++L.cnt);var n=document.createElement("div");n.setAttribute("id",L.id);n.setAttribute("data-cnt",L.cnt);n.className="__lxG__multi __lxG__multi_"+L.id;f[k].parentNode.insertBefore(n,f[k]);var C=1==L.cnt?B:B+"."+L.cnt;u[C]=L;J[C]={anchor:f[k],A:n};q++}})}});if(q){var B=k.replace("_",""),da=S(n.__lxGc__["s`"][k]),ea=S(u),ha=[];C(ea,function(f){ha.push(f)});
Mb({ids:ha},M,function(f,k,n){return function(k){var q=k.ids,u={};C(n,function(f){var k=S(n[f]);C(q,function(n,q){var u=q.old,C="_"+q["new"],B=q.cnt;if(u==f)return f=C,k.cnt=B,J[u].anchor.setAttribute("data-cnt",B),J[u].A.setAttribute("data-cnt",B),!1});u[f]=k});setTimeout(function(){Xa(f,u)},0)}}(B,da,ea),function(f,k,n){return function(){Xa(f,n)}}(B,da,ea))}})}};n.__lxGc__.f();"complete"!==da.readyState&&(n.__lxGc__.t=setInterval(n.__lxGc__.f,10),da.addEventListener("readystatechange",function(){"complete"==
da.readyState&&(clearInterval(n.__lxGc__.t),delete n.__lxGc__.t,n.__lxGc__.f())},!1))})();
